"""
Invoices — the financial document where payments are recorded.

Financial safety rules enforced here:
  • Once any payment is recorded, invoice amount and line items are LOCKED
    (only metadata — due_date, notes, client, project — can be edited).
  • Invoices with payments cannot be deleted; use PATCH /{id}/void instead.
  • Voided invoices are excluded from all financial totals but kept for audit.
  • Optimistic locking: every PUT includes the current version; a concurrent
    edit returns 409 Conflict so the user is told to refresh.
  • Payment idempotency: the frontend sends a UUID per submit; the server
    rejects exact duplicates (same key), preventing double-click double charges.
"""
from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel
from typing import Optional
from database import get_db
from permissions import require_perm
from routers.audit import log_action
from routers.promotions import apply_promotions_to_lines
from routers.finance import _check_period_locked
from routers.projects import bump_project_status
from approval_engine import evaluate_and_apply
from utils import _now, _today, get_tax_context, resolve_line_tax, money, notify
import accounting
import branch_access
import sqlite3
import uuid
from datetime import datetime, timedelta

router = APIRouter()

def _payment_total(db, invoice_id: int) -> float:
    row = db.execute(
        "SELECT COALESCE(SUM(amount), 0) AS total FROM invoice_payments WHERE invoice_id = ?",
        (invoice_id,),
    ).fetchone()
    return float(row["total"])

def _derive_status(amount: float, total_paid: float, voided_at=None) -> str:
    if voided_at:
        return "Void"
    if total_paid <= 0:
        return "Unpaid"
    if total_paid >= amount - 0.001:
        return "Paid"
    return "Partial"

def _is_overdue(due_date: Optional[str], payment_status: str) -> bool:
    if payment_status in ("Paid", "Void") or not due_date:
        return False
    return due_date < _today()

# ── Pydantic models ───────────────────────────────────────────────────────
class InvoiceItemCreate(BaseModel):
    name:        str
    quantity:    float = 1
    unit_price:  float = 0
    # Per-line discount in functional currency. Optional — defaults to 0
    # for callers (and customers) that don't use line discounts. The pricing
    # engine subtracts it from the net before computing tax.
    discount:    float = 0
    # Which stock item this line came from, when it was picked rather than
    # typed. Carries the promotion lookup — matching on `name` instead would
    # silently misprice the moment an item is renamed.
    inventory_id: Optional[int] = None
    # True when `discount` was NOT set by a human — the form left it to the
    # promotion. The server then derives the amount itself and snapshots which
    # promotion produced it.
    #
    # This flag exists so an explicit zero is possible. Without it the server
    # cannot tell "no discount typed" from "deliberately zero", and a customer
    # who was told they get no discount would silently receive the promotion
    # anyway. Defaults True so older callers keep the previous behaviour.
    # Optional[bool] rather than bool: a client that sends an explicit null
    # (the mobile app serialising an absent value) should mean "not set",
    # not fail validation on a field it never knew about.
    discount_auto: Optional[bool] = True
    # The percentage the operator typed, when they typed one. `discount` stays
    # the authoritative MONEY figure — the ledger and every issued document
    # depend on it — and is computed from this when it is present.
    #
    # None means "the amount was given directly": every line written before this
    # existed is in that state, and those documents must keep their exact money
    # rather than have it recomputed from a derived percentage.
    discount_pct: Optional[float] = None
    tax_rate_id: Optional[int] = None

class InvoiceCreate(BaseModel):
    quotation_id: Optional[int]  = None
    project_id:   Optional[int]  = None
    client_id:    Optional[int]  = None
    amount:       float          = 0
    due_date:     Optional[str]  = None
    notes:        Optional[str]  = None
    items:        Optional[list[InvoiceItemCreate]] = None
    version:      Optional[int]  = None   # required on PUT for optimistic locking
    branch_id:    Optional[int]  = None   # branch == warehouse; resolved on create

class PaymentCreate(BaseModel):
    amount:           float                   # value tendered, expressed in `currency`
    currency:         str   = "USD"           # 'USD' or 'LBP'
    exchange_rate:    Optional[float] = None  # LBP per USD — required when currency='LBP'
    method:           Optional[str] = "Cash"
    note:             Optional[str] = None
    cash_drawer_id:   Optional[int] = None    # which cash drawer received a cash payment
    idempotency_key:  str   # UUID required — generated by client via crypto.randomUUID()

class VoidRequest(BaseModel):
    reason: Optional[str] = "Voided"

# ── Helpers ───────────────────────────────────────────────────────────────
# Invoice numbers are derived from the row's own AUTOINCREMENT id, NOT from
# MAX(id)+1. The old MAX(id)+1 scheme read the current max and wrote a number
# in two non-atomic steps, so two concurrent creates could compute the SAME
# number and collide on the UNIQUE invoice_number constraint (one create then
# failed). Reserving the row first hands us an id that is unique by construction
# and never reused under AUTOINCREMENT, so the derived number is collision-free
# without any locking.
def _placeholder_invoice_number() -> str:
    """A guaranteed-unique temporary value to satisfy UNIQUE/NOT NULL for the
    instant between INSERT and the UPDATE that sets the real number."""
    return f"__pending__{uuid.uuid4().hex}"

def _invoice_prefix(db) -> str:
    from utils import get_setting
    # Empty or unset → default "INV-" (preserves prior behavior exactly).
    return get_setting(db, "invoice_prefix") or "INV-"

def _finalize_invoice_number(db, invoice_id: int, prefix: str) -> str:
    """Set the real, collision-free number on a freshly-inserted invoice row.
    Call right after the INSERT (before commit). Returns the number assigned."""
    inv_no = f"{prefix}{datetime.utcnow().year}-{invoice_id:04d}"
    db.execute("UPDATE invoices SET invoice_number=? WHERE id=?", (inv_no, invoice_id))
    return inv_no

def _apply_pending(row: dict) -> None:
    """An invoice awaiting approval is a draft: surface 'Pending Approval' as its
    display status and keep it off the overdue radar until it clears."""
    if row.get("approval_status") == "Pending Approval":
        row["payment_status"] = "Pending Approval"
        row["is_overdue"]     = False

def _enrich(row: dict, db) -> dict:
    total_paid = _payment_total(db, row["id"])
    amount     = float(row["amount"])
    row["total_paid"]     = money(total_paid)
    row["remaining"]      = money(amount - total_paid)
    row["payment_status"] = _derive_status(amount, total_paid, row.get("voided_at"))
    row["is_overdue"]     = _is_overdue(row.get("due_date"), row["payment_status"])
    _apply_pending(row)
    return row

def _table_exists(db, name):
    row = db.execute(
        "SELECT count(*) FROM sqlite_master WHERE type='table' AND name=?", (name,)
    ).fetchone()
    return row[0] > 0

def _ensure_invoice_items_table(db):
    db.execute("""
        CREATE TABLE IF NOT EXISTS invoice_items (
            id         INTEGER PRIMARY KEY AUTOINCREMENT,
            invoice_id INTEGER NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,
            name       TEXT    NOT NULL,
            quantity   REAL    NOT NULL DEFAULT 1,
            unit_price REAL    NOT NULL DEFAULT 0,
            discount   REAL    NOT NULL DEFAULT 0
        )
    """)
    db.commit()

def _has_payments(db, invoice_id: int) -> bool:
    row = db.execute(
        "SELECT COUNT(*) FROM invoice_payments WHERE invoice_id = ?", (invoice_id,)
    ).fetchone()
    return row[0] > 0

def _price_items(db, items, fallback_amount):
    """Roll up invoice line totals with per-line tax AND per-line discount.

    Per-line net is computed as `qty * unit_price - discount`, floored at 0.
    Tax is then computed on the discounted net (which matches how the rest of
    the world prices a discounted invoice — tax follows the customer's actual
    consideration, not the pre-discount sticker price). An itemless invoice
    treats `fallback_amount` as the net and applies the default rate.

    Returns (subtotal, tax_total, grand_total, line_tax) where line_tax is a
    list parallel to `items` of (tax_rate_id, tax_rate, tax_amount).
    """
    ctx = get_tax_context(db)
    line_tax = []
    if items:
        subtotal = tax_total = 0.0
        for it in items:
            qty   = float(getattr(it, "quantity", 0) or 0)
            price = float(getattr(it, "unit_price", 0) or 0)
            disc  = float(getattr(it, "discount", 0) or 0)
            # Per-line net at cents (after discount), tax is cent-rounded by
            # the helper. max(0,...) keeps an over-large discount from
            # producing a negative line that would distort the rollup.
            net = money(max(0.0, qty * price - disc))
            rid, rate, tax_amt = resolve_line_tax(ctx, it.tax_rate_id, net)
            subtotal  += net
            tax_total += tax_amt
            line_tax.append((rid, rate, tax_amt))
        # Header rollups are simple sums of cent-rounded lines, so they
        # always reconcile exactly with SUM(line.tax_amount).
        subtotal, tax_total = money(subtotal), money(tax_total)
    else:
        subtotal = money(fallback_amount or 0)
        _, _, tax_total = resolve_line_tax(ctx, None, subtotal)
    return subtotal, tax_total, money(subtotal + tax_total), line_tax


# ── List ──────────────────────────────────────────────────────────────────
@router.get("/")
def list_invoices(
    status: Optional[str] = None,
    include_archived: bool = False,
    branch_id: Optional[int] = None,
    limit: Optional[int] = None,
    offset: int = 0,
    user=Depends(require_perm("invoices", "view")),
    db: sqlite3.Connection = Depends(get_db),
):
    """List invoices.

    Backward-compatible pagination: with no `limit` the response is the full
    array exactly as before (the current UI and the finance aggregators rely on
    that). Pass `limit` (capped at 500) to get a `{items, total, limit, offset}`
    envelope instead — for scale-aware / programmatic consumers.
    """
    # `include_archived=1` returns archived invoices too (for the in-module
    # "Show archived" filter); the default view still hides them.
    conditions, params = [], []
    if not include_archived:
        conditions.append("i.archived_at IS NULL")
    # Branch scoping: restricted users see only their branches; admins may pass
    # branch_id to focus one branch, or omit it to see all.
    bf, bp = branch_access.branch_filter(user, db, column="i.branch_id", selected=branch_id)
    if bf:
        conditions.append(bf[len(" AND "):])   # branch_filter returns a leading " AND "
        params += bp
    where_clause = ("WHERE " + " AND ".join(conditions)) if conditions else ""
    select_sql = f"""SELECT i.*,
                  p.name AS project_name,
                  c.name AS client_name, c.phone AS client_phone,
                  q.quote_number,
                  COALESCE((SELECT SUM(ip.amount)
                            FROM invoice_payments ip
                            WHERE ip.invoice_id = i.id), 0) AS total_paid
           FROM invoices i
           LEFT JOIN projects   p ON i.project_id   = p.id
           LEFT JOIN clients    c ON i.client_id    = c.id
           LEFT JOIN quotations q ON i.quotation_id = q.id
           {where_clause}
           ORDER BY i.created_at DESC"""

    def _derive(r):
        d          = dict(r)
        total_paid = float(d["total_paid"])
        d["total_paid"]     = round(total_paid, 4)
        d["remaining"]      = round(float(d["amount"]) - total_paid, 4)
        d["payment_status"] = _derive_status(float(d["amount"]), total_paid, d.get("voided_at"))
        d["is_overdue"]     = _is_overdue(d.get("due_date"), d["payment_status"])
        _apply_pending(d)
        return d

    # Fast path: no `status` filter means the sort key + row set are plain
    # columns, so pagination pushes straight down to SQL (no full-table load).
    if limit is not None and not status:
        cap   = max(1, min(limit, 500))
        total = db.execute(
            f"SELECT COUNT(*) FROM invoices i {where_clause}", params
        ).fetchone()[0]
        rows = db.execute(select_sql + " LIMIT ? OFFSET ?", params + [cap, offset]).fetchall()
        return {"items": [_derive(r) for r in rows], "total": total,
                "limit": cap, "offset": offset}

    # `status` (Overdue / Void / a payment state) is derived AFTER the query, so
    # it can't be a SQL predicate — fetch, derive, then filter. When paginating,
    # slice the filtered set so `total` is the true post-filter count.
    result = [_derive(r) for r in db.execute(select_sql, params).fetchall()]
    if status == "Overdue":
        result = [r for r in result if r["is_overdue"]]
    elif status == "Void":
        result = [r for r in result if r["payment_status"] == "Void"]
    elif status:
        result = [r for r in result if r["payment_status"] == status and r["payment_status"] != "Void"]

    if limit is not None:
        cap = max(1, min(limit, 500))
        return {"items": result[offset:offset + cap], "total": len(result),
                "limit": cap, "offset": offset}
    return result

# ── Single ────────────────────────────────────────────────────────────────
@router.get("/{invoice_id}")
def get_invoice(
    invoice_id: int,
    user=Depends(require_perm("invoices", "view")),
    db: sqlite3.Connection = Depends(get_db),
):
    row = db.execute(
        """SELECT i.*, p.name AS project_name,
                  c.name AS client_name, c.phone AS client_phone, c.email AS client_email,
                  q.quote_number
           FROM invoices i
           LEFT JOIN projects   p ON i.project_id   = p.id
           LEFT JOIN clients    c ON i.client_id    = c.id
           LEFT JOIN quotations q ON i.quotation_id = q.id
           WHERE i.id = ?""",
        (invoice_id,),
    ).fetchone()
    if not row:
        raise HTTPException(404, "Invoice not found")
    branch_access.assert_can_view_branch(user, db, row["branch_id"])

    payments = db.execute(
        "SELECT * FROM invoice_payments WHERE invoice_id = ? ORDER BY paid_at DESC",
        (invoice_id,),
    ).fetchall()

    items = db.execute(
        "SELECT * FROM invoice_items WHERE invoice_id = ? ORDER BY id",
        (invoice_id,),
    ).fetchall() if _table_exists(db, "invoice_items") else []

    d = _enrich(dict(row), db)
    d["payments"] = [dict(p) for p in payments]
    d["items"]    = [dict(i) for i in items]
    d["amounts_locked"] = _has_payments(db, invoice_id)
    return d

# ── Create ────────────────────────────────────────────────────────────────
@router.post("/")
def create_invoice(
    data: InvoiceCreate,
    user=Depends(require_perm("invoices", "create")),
    db: sqlite3.Connection = Depends(get_db),
):
    _ensure_invoice_items_table(db)
    # Validate foreign relations up front: a stale id must return a clean 400,
    # never an unhandled FOREIGN KEY IntegrityError (HTTP 500).
    if data.client_id is not None and not db.execute(
        "SELECT 1 FROM clients WHERE id=?", (data.client_id,)).fetchone():
        raise HTTPException(400, "Client not found")
    if data.project_id is not None and not db.execute(
        "SELECT 1 FROM projects WHERE id=?", (data.project_id,)).fetchone():
        raise HTTPException(400, "Project not found")
    if data.quotation_id is not None and not db.execute(
        "SELECT 1 FROM quotations WHERE id=?", (data.quotation_id,)).fetchone():
        raise HTTPException(400, "Quotation not found")
    items    = data.items or []
    # Promotions fill an empty line discount BEFORE pricing, so tax lands on the
    # discounted net exactly as it does for a hand-entered discount. The
    # quantity cap is deliberately NOT consumed here — an invoice can be
    # drafted, edited and voided, so metering it would burn units of a promotion
    # the customer may never receive. POS stays the metered channel.
    promo_ids = apply_promotions_to_lines(db, items)
    subtotal, tax_total, computed_amount, line_tax = _price_items(db, items, data.amount)
    if computed_amount <= 0:
        raise HTTPException(400, "Invoice amount must be positive")
    now      = _now()
    due_date = data.due_date
    if not due_date:
        terms_row = db.execute("SELECT value FROM settings WHERE key='payment_terms_days'").fetchone()
        days = int(terms_row["value"]) if terms_row else 15
        due_date = (datetime.utcnow() + timedelta(days=days)).strftime("%Y-%m-%d")
    # Reserve the row first (placeholder number), then derive the real number
    # from its id — see the helper notes; this is what makes concurrent creates
    # collision-free.
    branch_id = branch_access.resolve_branch_id(user, db, data.branch_id)
    cur = db.execute(
        "INSERT INTO invoices "
        "(invoice_number, quotation_id, project_id, client_id, amount, subtotal, tax_total, "
        " due_date, notes, created_at, version, branch_id) "
        "VALUES (?,?,?,?,?,?,?,?,?,?,1,?)",
        (_placeholder_invoice_number(), data.quotation_id, data.project_id, data.client_id,
         computed_amount, subtotal, tax_total, due_date, data.notes, now, branch_id),
    )
    invoice_id = cur.lastrowid
    inv_no     = _finalize_invoice_number(db, invoice_id, _invoice_prefix(db))
    for idx, item in enumerate(items):
        rid, rate, tax_amt = line_tax[idx]
        db.execute(
            "INSERT INTO invoice_items "
            "(invoice_id, name, quantity, unit_price, discount, discount_pct, tax_rate_id, "
            " tax_rate, tax_amount, inventory_id, promotion_id) "
            "VALUES (?,?,?,?,?,?,?,?,?,?,?)",
            (invoice_id, item.name, item.quantity, item.unit_price,
             float(getattr(item, "discount", 0) or 0),
             getattr(item, "discount_pct", None),
             rid, rate, tax_amt,
             getattr(item, "inventory_id", None),
             promo_ids[idx] if idx < len(promo_ids) else None),
        )
    # An active policy can gate the invoice behind approval. A gated invoice is
    # parked in 'Pending Approval' (it takes no payments and its project advance
    # is deferred to approval — see approval_engine.apply_resolution).
    entity_data = {
        "amount":    float(computed_amount or 0),
        "subtotal":  float(subtotal or 0),
        "tax_total": float(tax_total or 0),
    }
    needs_approval = evaluate_and_apply(
        db, module="invoice", action="create",
        entity_data=entity_data, user_id=user["id"],
        entity_id=invoice_id, entity_label=inv_no,
    )
    if needs_approval:
        db.execute("UPDATE invoices SET approval_status='Pending Approval' WHERE id=?",
                   (invoice_id,))
    else:
        # Auto-advance the linked project's status to Invoiced (forward-only).
        bump_project_status(db, data.project_id, "Invoiced")

    log_action(db, user, "create", "invoice", invoice_id, inv_no,
               {"amount": computed_amount})
    db.commit()
    return {
        "id": invoice_id, "invoice_number": inv_no,
        "pending_approval": bool(needs_approval),
        "message": "Invoice pending approval" if needs_approval else "Invoice created",
    }

# ── Update ────────────────────────────────────────────────────────────────
@router.put("/{invoice_id}")
def update_invoice(
    invoice_id: int,
    data: InvoiceCreate,
    user=Depends(require_perm("invoices", "edit")),
    db: sqlite3.Connection = Depends(get_db),
):
    _ensure_invoice_items_table(db)
    inv = db.execute(
        "SELECT * FROM invoices WHERE id = ? AND archived_at IS NULL", (invoice_id,)
    ).fetchone()
    if not inv:
        raise HTTPException(404, "Invoice not found")
    if inv["voided_at"]:
        raise HTTPException(400, "Voided invoices cannot be edited.")
    # A finalised (locked-month / closed-year) invoice can't be edited.
    _check_period_locked(db, inv["created_at"])

    # ── Optimistic locking ────────────────────────────────────────────────
    if data.version is not None and data.version != inv["version"]:
        raise HTTPException(
            409,
            "This invoice was modified by another user. Please refresh and try again."
        )

    has_payments = _has_payments(db, invoice_id)

    if has_payments:
        # Amounts are LOCKED once payments exist — only metadata may change
        db.execute(
            "UPDATE invoices "
            "SET quotation_id=?, project_id=?, client_id=?, due_date=?, notes=?, "
            "    version=version+1 "
            "WHERE id=? AND version=?",
            (data.quotation_id, data.project_id, data.client_id,
             data.due_date, data.notes,
             invoice_id, inv["version"]),
        )
        if db.execute("SELECT changes()").fetchone()[0] == 0:
            raise HTTPException(409, "This invoice was modified by another user. Please refresh and try again.")
        log_action(db, user, "update", "invoice", invoice_id,
                   inv["invoice_number"], {"note": "metadata only — amounts locked"})
    else:
        items    = data.items or []
        promo_ids = apply_promotions_to_lines(db, items)
        subtotal, tax_total, computed_amount, line_tax = _price_items(db, items, data.amount)

        rows_updated = db.execute(
            "UPDATE invoices "
            "SET quotation_id=?, project_id=?, client_id=?, amount=?, subtotal=?, tax_total=?, "
            "    due_date=?, notes=?, version=version+1 "
            "WHERE id=? AND version=?",
            (data.quotation_id, data.project_id, data.client_id,
             computed_amount, subtotal, tax_total, data.due_date, data.notes,
             invoice_id, inv["version"]),
        ).rowcount
        if rows_updated == 0:
            raise HTTPException(409, "This invoice was modified by another user. Please refresh and try again.")

        db.execute("DELETE FROM invoice_items WHERE invoice_id=?", (invoice_id,))
        for idx, item in enumerate(items):
            rid, rate, tax_amt = line_tax[idx]
            # `discount` must be written here too. It was omitted, so editing an
            # invoice silently reset every per-line discount to 0 while the
            # stored total kept the discounted figure — a document that no
            # longer added up, and a customer quietly losing the discount they
            # were given.
            db.execute(
                "INSERT INTO invoice_items "
                "(invoice_id, name, quantity, unit_price, discount, discount_pct, tax_rate_id, "
                " tax_rate, tax_amount, inventory_id, promotion_id) "
                "VALUES (?,?,?,?,?,?,?,?,?,?,?)",
                (invoice_id, item.name, item.quantity, item.unit_price,
                 float(getattr(item, "discount", 0) or 0),
                 getattr(item, "discount_pct", None),
                 rid, rate, tax_amt,
                 getattr(item, "inventory_id", None),
                 promo_ids[idx] if idx < len(promo_ids) else None),
            )
        log_action(db, user, "update", "invoice", invoice_id,
                   inv["invoice_number"], {"amount": computed_amount})

    db.commit()
    return {"message": "Invoice updated"}

# ── Void (replaces delete for invoices with payments) ─────────────────────
@router.patch("/{invoice_id}/void")
def void_invoice(
    invoice_id: int,
    data: VoidRequest,
    user=Depends(require_perm("invoices", "delete")),
    db: sqlite3.Connection = Depends(get_db),
):
    inv = db.execute(
        "SELECT * FROM invoices WHERE id = ? AND archived_at IS NULL", (invoice_id,)
    ).fetchone()
    if not inv:
        raise HTTPException(404, "Invoice not found")
    if inv["voided_at"]:
        raise HTTPException(400, "Invoice is already voided.")
    # Can't void an invoice that belongs to a locked month / closed year —
    # reopen the period (or post a credit note in an open one) instead.
    _check_period_locked(db, inv["created_at"])
    now = _now()
    db.execute(
        "UPDATE invoices SET voided_at=?, void_reason=?, version=version+1 WHERE id=?",
        (now, data.reason or "Voided", invoice_id),
    )
    # NOTE: no projects.actual_cost adjustment here. Invoices are project
    # REVENUE — only expenses feed actual_cost (see routers/finance.py), and
    # invoice creation never increments it, so there is nothing to walk back.
    # Reverse the ledger entry for every payment on the voided invoice so the
    # books no longer recognise the revenue.
    for pay in db.execute(
        "SELECT id FROM invoice_payments WHERE invoice_id=?", (invoice_id,)
    ).fetchall():
        accounting.reverse_source(db, "invoice_payment", pay["id"],
                                  memo=f"Reversal — voided invoice {inv['invoice_number']}",
                                  created_by=user["id"])
    log_action(db, user, "void", "invoice", invoice_id,
               inv["invoice_number"], {"reason": data.reason or "Voided"})
    db.commit()
    return {"message": "Invoice voided", "voided_at": now}


@router.patch("/{invoice_id}/unvoid")
def unvoid_invoice(
    invoice_id: int,
    user=Depends(require_perm("invoices", "delete")),
    db: sqlite3.Connection = Depends(get_db),
):
    """Reverse a void: the invoice returns to all financial totals and the
    ledger entry for every payment is re-posted (void had reversed them).

    POS-sale invoices are excluded — a POS return already restocked the
    goods and is final; unvoiding here would desync stock and COGS."""
    inv = db.execute(
        "SELECT * FROM invoices WHERE id = ? AND archived_at IS NULL", (invoice_id,)
    ).fetchone()
    if not inv:
        raise HTTPException(404, "Invoice not found")
    if not inv["voided_at"]:
        raise HTTPException(400, "Invoice is not voided.")
    if db.execute("SELECT 1 FROM pos_sales WHERE invoice_id=?", (invoice_id,)).fetchone():
        raise HTTPException(
            400, "POS-sale invoices cannot be unvoided — the POS return already "
                 "restocked the goods. Ring the sale up again instead.")
    # Same period rules as void: the invoice's month and today's (where the
    # re-recognition entries land) must both be open.
    _check_period_locked(db, inv["created_at"])
    _check_period_locked(db, _now())

    db.execute(
        "UPDATE invoices SET voided_at=NULL, void_reason=NULL, version=version+1 WHERE id=?",
        (invoice_id,),
    )
    # Re-recognise every payment in the ledger. The void reversed the live
    # entry per payment, so post_entry's idempotency guard sees no live entry
    # and a fresh posting goes through — the GL history keeps all three
    # movements (original, reversal, re-recognition) for the audit trail.
    today = _now()[:10]
    for pay in db.execute(
        "SELECT * FROM invoice_payments WHERE invoice_id=?", (invoice_id,)
    ).fetchall():
        accounting.post_entry(
            db,
            entry_date=today,
            memo=f"Unvoid — payment re-recognised — {inv['invoice_number']}",
            lines=[
                {"code": accounting.cash_account_for(pay["paid_currency"]),
                 "debit": float(pay["amount"]),
                 "memo": f"{pay['method']} ({pay['paid_currency'] or 'USD'})"},
                {"code": accounting.REVENUE, "credit": float(pay["amount"])},
            ],
            source_type="invoice_payment", source_id=pay["id"], created_by=user["id"],
            branch_id=inv["branch_id"],
        )
    log_action(db, user, "unvoid", "invoice", invoice_id, inv["invoice_number"])
    db.commit()
    return {"message": "Invoice restored"}


# ── Add payment ───────────────────────────────────────────────────────────
@router.post("/{invoice_id}/payments")
def add_payment(
    invoice_id: int,
    data: PaymentCreate,
    user=Depends(require_perm("invoices", "create")),
    db: sqlite3.Connection = Depends(get_db),
):
    if data.amount <= 0:
        raise HTTPException(400, "Payment amount must be positive")

    # ── Resolve the currency the client paid in ───────────────────────────
    # `amount` is what the client tendered, in `currency`. The invoice balance
    # is always tracked in USD, so an LBP payment is converted at the rate the
    # user supplies; `usd_amount` is what reduces the balance.
    currency = (data.currency or "USD").upper()
    if currency not in ("USD", "LBP"):
        raise HTTPException(400, "Unsupported payment currency")
    if currency == "LBP":
        # F-9 audit fix: if the caller omits exchange_rate, fall back to the
        # latest rate stored in `exchange_rates` so manual data entry can't
        # accidentally apply yesterday's rate or no rate at all. The supplied
        # rate still takes precedence (and is stored on the payment) so an
        # accountant can override when a contract dictates a different rate.
        if not data.exchange_rate or data.exchange_rate <= 0:
            rate_row = db.execute(
                "SELECT rate FROM exchange_rates ORDER BY id DESC LIMIT 1"
            ).fetchone()
            if not rate_row or not rate_row["rate"]:
                raise HTTPException(
                    400,
                    "An exchange rate is required for LBP payments. No rate is "
                    "configured — set one in Settings → Exchange Rate first."
                )
            rate = float(rate_row["rate"])
        else:
            rate = float(data.exchange_rate)
        usd_amount  = money(data.amount / rate)
        paid_amount = data.amount
    else:
        rate        = None
        usd_amount  = money(data.amount)
        paid_amount = data.amount
    if usd_amount <= 0:
        raise HTTPException(400, "Payment amount must be positive")

    inv = db.execute(
        "SELECT * FROM invoices WHERE id = ? AND archived_at IS NULL", (invoice_id,)
    ).fetchone()
    if not inv:
        raise HTTPException(404, "Invoice not found")
    if inv["voided_at"]:
        raise HTTPException(400, "Cannot add payments to a voided invoice.")
    if inv["approval_status"] == "Pending Approval":
        raise HTTPException(400, "Cannot record payments on an invoice awaiting approval.")

    _check_period_locked(db, _now()[:7] + "-01")

    # ── Idempotency check ─────────────────────────────────────────────────
    if data.idempotency_key:
        existing = db.execute(
            "SELECT id FROM invoice_payments WHERE idempotency_key = ?",
            (data.idempotency_key,),
        ).fetchone()
        if existing:
            raise HTTPException(409, "This payment was already recorded (duplicate submission).")

    total_paid = _payment_total(db, invoice_id)
    remaining  = money(float(inv["amount"]) - total_paid)

    if usd_amount > remaining + 0.001:
        raise HTTPException(
            400,
            f"Payment ${usd_amount:.2f} exceeds remaining balance ${remaining:.2f}",
        )

    # A cash payment may be attributed to a specific cash drawer.
    drawer_id = data.cash_drawer_id if (data.method or "").strip().lower() == "cash" else None
    if drawer_id is not None and not db.execute(
        "SELECT 1 FROM cash_drawers WHERE id=?", (drawer_id,)).fetchone():
        raise HTTPException(400, "Cash drawer not found")

    pay_cur = db.execute(
        "INSERT INTO invoice_payments "
        "(invoice_id, amount, method, note, paid_at, idempotency_key, "
        " paid_currency, paid_amount, exchange_rate, cash_drawer_id) "
        "VALUES (?,?,?,?,?,?,?,?,?,?)",
        (invoice_id, usd_amount, data.method, data.note, _now(), data.idempotency_key,
         currency, paid_amount, rate, drawer_id),
    )
    payment_id = pay_cur.lastrowid

    # Auto-post to the general ledger: cash-basis revenue recognition.
    # The cash account is selected by the tendered currency (F-5 audit fix):
    # USD payments hit "1000 Cash & Bank", LBP payments hit "1010 Cash — LBP".
    # Keeping them on distinct ledger lines is required by IAS 21 so each
    # monetary holding can be revalued at the spot rate at period end.
    accounting.post_entry(
        db,
        entry_date=_now()[:10],
        memo=f"Payment received — {inv['invoice_number']}",
        lines=[
            {"code": accounting.cash_account_for(currency),
             "debit":  usd_amount, "memo": f"{data.method} ({currency})"},
            {"code": accounting.REVENUE, "credit": usd_amount},
        ],
        source_type="invoice_payment", source_id=payment_id, created_by=user["id"],
        branch_id=inv["branch_id"],
    )
    log_action(db, user, "payment", "invoice", invoice_id, inv["invoice_number"],
               {"amount": usd_amount, "method": data.method,
                "currency": currency, "paid_amount": paid_amount})

    new_paid   = money(total_paid + usd_amount)
    new_remain = money(float(inv["amount"]) - new_paid)
    new_status = _derive_status(float(inv["amount"]), new_paid)

    client_row = db.execute("SELECT name FROM clients WHERE id=?", (inv["client_id"],)).fetchone() if inv["client_id"] else None
    client_name = client_row["name"] if client_row else "Unknown client"

    if new_status == "Paid":
        notify(db, type="invoice_paid",
               title=f"Invoice {inv['invoice_number']} fully paid",
               body=f"{client_name} — ${float(inv['amount']):,.2f} received via {data.method}",
               msg="invoice_paid", params={"number": inv["invoice_number"], "client": client_name,
                                           "amount": float(inv["amount"]), "method": data.method},
               link=f"/invoices/{invoice_id}", entity_type="invoice", entity_id=invoice_id)
    else:
        notify(db, type="payment_received",
               title=f"Payment received on {inv['invoice_number']}",
               body=f"{client_name} — ${usd_amount:,.2f} via {data.method} · ${new_remain:,.2f} remaining",
               msg="payment_received", params={"number": inv["invoice_number"], "client": client_name,
                                               "amount": float(usd_amount), "method": data.method,
                                               "remaining": float(new_remain)},
               link=f"/invoices/{invoice_id}", entity_type="invoice", entity_id=invoice_id)

    db.commit()
    return {
        "message":    "Payment recorded",
        "total_paid": new_paid,
        "remaining":  new_remain,
        "status":     new_status,
    }

# ── List payments ─────────────────────────────────────────────────────────
@router.get("/{invoice_id}/payments")
def list_payments(
    invoice_id: int,
    user=Depends(require_perm("invoices", "view")),
    db: sqlite3.Connection = Depends(get_db),
):
    rows = db.execute(
        "SELECT * FROM invoice_payments WHERE invoice_id = ? ORDER BY paid_at DESC",
        (invoice_id,),
    ).fetchall()
    return [dict(r) for r in rows]

# ── Delete payment ────────────────────────────────────────────────────────
@router.delete("/{invoice_id}/payments/{payment_id}")
def delete_payment(
    invoice_id: int,
    payment_id: int,
    user=Depends(require_perm("invoices", "delete")),
    db: sqlite3.Connection = Depends(get_db),
):
    inv = db.execute(
        "SELECT * FROM invoices WHERE id = ? AND archived_at IS NULL", (invoice_id,)
    ).fetchone()
    if not inv:
        raise HTTPException(404, "Invoice not found")
    if inv["voided_at"]:
        raise HTTPException(400, "Cannot modify payments on a voided invoice.")

    row = db.execute(
        "SELECT * FROM invoice_payments WHERE id = ? AND invoice_id = ?",
        (payment_id, invoice_id),
    ).fetchone()
    if not row:
        raise HTTPException(404, "Payment not found")
    _check_period_locked(db, str(row["paid_at"])[:7] + "-01")

    # Reverse the ledger entry posted when this payment was recorded.
    accounting.reverse_source(db, "invoice_payment", payment_id,
                              memo=f"Reversal — deleted payment on {inv['invoice_number']}",
                              created_by=user["id"])
    db.execute("DELETE FROM invoice_payments WHERE id = ?", (payment_id,))
    log_action(db, user, "delete_payment", "invoice", invoice_id,
               inv["invoice_number"], {"amount": float(row["amount"])})
    db.commit()
    return {"message": "Payment deleted"}

# ── Archive invoice (only for draft invoices with zero payments) ──────────
@router.patch("/{invoice_id}/archive")
def archive_invoice(
    invoice_id: int,
    user=Depends(require_perm("invoices", "delete")),
    db: sqlite3.Connection = Depends(get_db),
):
    inv = db.execute(
        "SELECT * FROM invoices WHERE id = ? AND archived_at IS NULL", (invoice_id,)
    ).fetchone()
    if not inv:
        raise HTTPException(404, "Invoice not found")
    if _has_payments(db, invoice_id):
        raise HTTPException(
            400,
            "Cannot archive an invoice with recorded payments. Use 'Void' instead to preserve the audit trail."
        )
    now = _now()
    db.execute(
        "UPDATE invoices SET archived_at=?, archive_reason='Archived' WHERE id=?",
        (now, invoice_id)
    )
    log_action(db, user, "archive", "invoice", invoice_id, inv["invoice_number"])
    db.commit()
    return {"message": "Invoice archived"}

@router.patch("/{invoice_id}/unarchive")
def unarchive_invoice(
    invoice_id: int,
    user=Depends(require_perm("invoices", "edit")),
    db: sqlite3.Connection = Depends(get_db),
):
    inv = db.execute(
        "SELECT * FROM invoices WHERE id = ? AND archived_at IS NOT NULL", (invoice_id,)
    ).fetchone()
    if not inv:
        raise HTTPException(404, "Invoice not found in archives")
    db.execute("UPDATE invoices SET archived_at=NULL, archive_reason=NULL WHERE id=?", (invoice_id,))
    log_action(db, user, "unarchive", "invoice", invoice_id, inv["invoice_number"])
    db.commit()
    return {"message": "Invoice restored from archive"}
