from dotenv import load_dotenv
from pathlib import Path
load_dotenv(Path(__file__).parent / ".env")

import os, sys
if not os.environ.get("SECRET_KEY"):
    sys.exit(
        "\n  FATAL: SECRET_KEY environment variable is not set.\n"
        "  Generate one with:  python -c \"import secrets; print(secrets.token_hex(32))\"\n"
        "  Add it to backend/.env as:  SECRET_KEY=<generated-value>\n"
    )

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
import os

from routers import clients, projects, quotations, inventory, invoices, finance, dashboard, auth
from routers import communications as communications_router
from routers import pdf as pdf_router
from routers import purchases, settings, documents, suppliers, audit, users, roles, search
from routers import reports, crm, planning, notifications
from routers import approval_policies, approval_requests, hr, hr_contracts, recruitment, hr_activities, tax_rates, pos, cash, manufacturing
from routers import assets, recurring, announcements, attachments, accounting, warehouses, platform, imports
from routers import products
from routers import support as support_router
from routers import categories as categories_router, promotions

# Structured logging (JSON when LOG_FORMAT=json) + per-request correlation ids.
# Configured before the app so startup logs are formatted too.
from logging_setup import configure_logging, RequestContextMiddleware
configure_logging()

# Interactive API docs are a development tool. On a multi-tenant deployment they
# publish the complete API surface — every endpoint, every field name — to
# anyone who asks, unauthenticated. That does not grant access (the endpoints
# still require auth) but it hands an attacker a finished map, so the cloud
# deployment turns them off.
#
# The switch is on TENANCY rather than a new variable: schema mode IS the hosted
# multi-tenant product, and the self-hosted/desktop build keeps the docs it has
# always had. API_DOCS=on forces them back for debugging a cloud instance.
_DOCS = (os.environ.get("API_DOCS", "").strip().lower() in ("1", "on", "true")
         or os.environ.get("TENANCY", "single").strip().lower()
         not in ("schema", "multi", "tenant"))

app = FastAPI(title="ERP System", version="2.0.0",
              docs_url="/docs" if _DOCS else None,
              redoc_url="/redoc" if _DOCS else None,
              openapi_url="/openapi.json" if _DOCS else None)

# Turn known bad-input failures (bad FKs, absurd amounts) into clean 4xx
# instead of 500s — see error_handlers.py.
from error_handlers import register_error_handlers
register_error_handlers(app)

# Allow origins from env var (comma-separated) or fall back to localhost for dev
_raw_origins = os.environ.get("ALLOWED_ORIGINS", "http://localhost:5173,http://localhost:3000")
ALLOWED_ORIGINS = [o.strip() for o in _raw_origins.split(",") if o.strip()]

app.add_middleware(
    CORSMiddleware,
    allow_origins=ALLOWED_ORIGINS,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Schema-per-tenant routing (Phase 2). Self-disables unless TENANCY=schema, so
# single-tenant / desktop installs are completely unaffected.
from tenancy import TenantMiddleware
from tenant_context import IS_SCHEMA_TENANCY
app.add_middleware(TenantMiddleware)


# ── Security response headers ────────────────────────────────────────────────
# Hardening headers on every response: block MIME-sniffing, framing
# (clickjacking), and constrain resource loading (defense-in-depth XSS). Pure
# ASGI (not BaseHTTPMiddleware) so it never interferes with streaming/file
# responses. The SPA is served same-origin with NO inline scripts (Vite emits
# external module scripts), so `script-src 'self'` is safe; React inline styles
# need `style-src 'unsafe-inline'`.
_CSP_APP = (
    b"default-src 'self'; base-uri 'self'; frame-ancestors 'none'; "
    b"object-src 'none'; img-src 'self' data: blob:; font-src 'self' data:; "
    b"style-src 'self' 'unsafe-inline'; script-src 'self'; "
    b"connect-src 'self'; form-action 'self'")

# The manual is generated by MkDocs Material, which bootstraps itself from an
# inline <script> — under `script-src 'self'` that script is blocked, and with
# it the search, the theme toggle and the audience tabs that every page is built
# around. The page then renders as one long undifferentiated wall.
#
# So /manual/ gets 'unsafe-inline' for scripts and nothing else. It is worth
# being precise about what that does and does not risk: these pages are static
# HTML compiled from Markdown in this repository at build time. They render no
# user input, hold no session, and issue no API calls, so there is nothing on
# them for injected script to steal or forge. Every other directive — including
# `connect-src 'self'` and `frame-ancestors 'none'` — stays exactly as strict,
# and the ERP's own pages keep the unmodified policy.
_CSP_MANUAL = _CSP_APP.replace(b"script-src 'self'",
                               b"script-src 'self' 'unsafe-inline'")


class SecurityHeadersMiddleware:
    def __init__(self, app, hsts: bool):
        self.app = app
        self._headers = [
            (b"x-content-type-options", b"nosniff"),
            (b"x-frame-options", b"DENY"),
            (b"referrer-policy", b"strict-origin-when-cross-origin"),
            (b"content-security-policy", _CSP_APP),
        ]
        # HSTS only over HTTPS deployments (COOKIE_SECURE=true). Browsers ignore
        # it over plain HTTP anyway, but sending it only when secure avoids
        # surprising LAN-only self-hosted installs served on http://.
        if hsts:
            self._headers.append(
                (b"strict-transport-security", b"max-age=31536000; includeSubDomains"))

    async def __call__(self, scope, receive, send):
        if scope["type"] != "http":
            await self.app(scope, receive, send)
            return

        is_manual = scope.get("path", "").startswith("/manual/")

        async def _send(message):
            if message["type"] == "http.response.start":
                headers = message.setdefault("headers", [])
                present = {k.lower() for k, _ in headers}
                for k, v in self._headers:
                    if k not in present:
                        headers.append((k, v if k != b"content-security-policy"
                                        or not is_manual else _CSP_MANUAL))
            await send(message)

        await self.app(scope, receive, _send)


class MetricsMiddleware:
    """Per-tenant API usage and latency (see metrics.py).

    Pure ASGI so the response status can be read from the outgoing
    http.response.start message without buffering the body — wrapping this as
    a BaseHTTPMiddleware would materialise every response, which is exactly
    the cost telemetry must not add.

    The hot path is a timer plus a dict increment. The periodic flush runs
    AFTER the response has been sent, so a customer's request never waits on
    a metrics write. Every failure is swallowed: telemetry must never take the
    ERP down.
    """

    def __init__(self, app):
        self.app = app

    async def __call__(self, scope, receive, send):
        if scope.get("type") != "http" or not IS_SCHEMA_TENANCY:
            await self.app(scope, receive, send)
            return

        import time as _time
        started = _time.perf_counter()
        status_holder = {"code": 0, "schema": None}

        async def _send(message):
            if message.get("type") == "http.response.start":
                status_holder["code"] = message.get("status", 0)
                # Capture the tenant HERE, not in the finally below. This
                # middleware is registered outside TenantMiddleware, whose own
                # finally resets the ContextVar first — so by the time our
                # finally runs, current_schema() is always None. At
                # response.start the inner middleware is still on the stack and
                # the context is live.
                try:
                    from tenant_context import current_schema
                    status_holder["schema"] = current_schema()
                except Exception:
                    pass
            await send(message)

        try:
            await self.app(scope, receive, _send)
        finally:
            try:
                import metrics
                schema = status_holder.get("schema")
                if schema:
                    # tenant_<slug> -> slug
                    slug = schema[7:] if schema.startswith("tenant_") else schema
                    metrics.record(slug, status_holder["code"],
                                   (_time.perf_counter() - started) * 1000.0)
                # Response is already sent by here, so this costs the customer
                # nothing.
                if metrics.due_for_flush():
                    metrics.flush()
                    metrics.snapshot_storage_if_due()
            except Exception:
                pass


from auth_utils import COOKIE_SECURE
app.add_middleware(SecurityHeadersMiddleware, hsts=COOKIE_SECURE)

# Added last → outermost: it assigns the request id before any other middleware
# or handler runs, so every log line for the request is correlated.
app.add_middleware(MetricsMiddleware)
app.add_middleware(RequestContextMiddleware)

app.include_router(auth.router,        prefix="/api/auth",        tags=["auth"])
app.include_router(dashboard.router,   prefix="/api/dashboard",   tags=["dashboard"])
app.include_router(clients.router,     prefix="/api/clients",     tags=["clients"])
app.include_router(projects.router,    prefix="/api/projects",    tags=["projects"])
app.include_router(quotations.router,  prefix="/api/quotations",  tags=["quotations"])
app.include_router(inventory.router,   prefix="/api/inventory",   tags=["inventory"])
app.include_router(invoices.router,    prefix="/api/invoices",    tags=["invoices"])
app.include_router(finance.router,     prefix="/api/finance",     tags=["finance"])
app.include_router(purchases.router,     prefix="/api/purchases",     tags=["purchases"])
app.include_router(settings.router,      prefix="/api/settings",      tags=["settings"])
app.include_router(documents.router,     prefix="/api/documents",     tags=["documents"])
app.include_router(suppliers.router,     prefix="/api/suppliers",     tags=["suppliers"])
app.include_router(audit.router,         prefix="/api/audit",         tags=["audit"])
app.include_router(users.router,         prefix="/api/users",          tags=["users"])
app.include_router(roles.router,         prefix="/api/roles",          tags=["roles"])
app.include_router(search.router,        prefix="/api/search",         tags=["search"])
app.include_router(reports.router,       prefix="/api/reports",        tags=["reports"])
app.include_router(crm.router,           prefix="/api/crm",            tags=["crm"])
app.include_router(planning.router,      prefix="/api/planning",       tags=["planning"])
app.include_router(notifications.router,     prefix="/api/notifications",      tags=["notifications"])
app.include_router(approval_policies.router, prefix="/api/approval-policies",  tags=["approvals"])
app.include_router(approval_requests.router, prefix="/api/approval-requests",  tags=["approvals"])
app.include_router(hr.router,                prefix="/api/hr",                 tags=["hr"])
app.include_router(hr_contracts.router,      prefix="/api/hr/contracts",       tags=["hr"])
app.include_router(recruitment.router,       prefix="/api/recruitment",        tags=["recruitment"])
app.include_router(hr_activities.router,     prefix="/api/hr-activities",      tags=["hr"])
app.include_router(tax_rates.router,         prefix="/api/tax-rates",          tags=["tax"])
app.include_router(pos.router,               prefix="/api/pos",                tags=["pos"])
app.include_router(cash.router,              prefix="/api/cash",               tags=["cash"])
app.include_router(manufacturing.router,     prefix="/api/manufacturing",      tags=["manufacturing"])
app.include_router(assets.router,            prefix="/api/assets",             tags=["assets"])
app.include_router(recurring.router,         prefix="/api/recurring-expenses", tags=["expenses"])
app.include_router(announcements.router,      prefix="/api/announcements",      tags=["announcements"])
app.include_router(attachments.router,        prefix="/api/attachments",        tags=["attachments"])
app.include_router(accounting.router,         prefix="/api/accounting",         tags=["accounting"])
app.include_router(warehouses.router,         prefix="/api/warehouses",         tags=["warehouses"])
app.include_router(platform.router,           prefix="/api/platform",           tags=["platform"])
app.include_router(imports.router,            prefix="/api/imports",            tags=["imports"])
app.include_router(support_router.router, prefix="/api/support",  tags=["support"])
app.include_router(products.router,           prefix="/api/products",           tags=["products"])
app.include_router(categories_router.router,  prefix="/api/categories",         tags=["categories"])
app.include_router(promotions.router,         prefix="/api/promotions",         tags=["promotions"])
app.include_router(communications_router.router, prefix="/api/communications", tags=["communications"])
app.include_router(pdf_router.router, prefix="/api/pdf", tags=["pdf"])

def _build_commit() -> str:
    """The commit this process is running, resolved ONCE at import.

    Deploys were otherwise unverifiable from outside: after pushing a security
    fix the only way to tell whether it was live was to trigger the bug, which
    is not something you do against a customer's workspace. One curl of
    /api/health now answers it.

    The runtime image has no .git — `backend/` is COPYed in — so the host's
    build variable is the real source and git is only a development fallback.
    Railway sets RAILWAY_GIT_COMMIT_SHA itself; the others cover Render, Heroku
    and a plain `docker build --build-arg`.
    """
    for var in ("RAILWAY_GIT_COMMIT_SHA", "GIT_COMMIT",
                "SOURCE_VERSION", "COMMIT_SHA"):
        value = (os.environ.get(var) or "").strip()
        if value:
            return value[:12]

    # Development fallback. Guarded by a .git check so the subprocess never
    # runs in a container, and time-boxed so a wedged git cannot delay startup
    # (this runs at import, before the health check can answer).
    repo = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    if os.path.isdir(os.path.join(repo, ".git")):
        try:
            import subprocess
            out = subprocess.run(["git", "rev-parse", "--short=12", "HEAD"],
                                 cwd=repo, capture_output=True, text=True,
                                 timeout=2)
            if out.returncode == 0 and out.stdout.strip():
                return out.stdout.strip()
        except Exception:
            pass
    return "unknown"


BUILD_COMMIT = _build_commit()


@app.get("/api/health")
def health():
    """Liveness probe for containers / load balancers (no DB hit).

    `commit` is resolved at import, so this stays a constant-time response and
    a probe every few seconds costs nothing.
    """
    return {"status": "ok", "commit": BUILD_COMMIT}

# ── Serve the built SPA (single-service hosts: Render, Fly, a bare VM…) ───────
# In the Docker Compose stack, Caddy serves the SPA and reverse-proxies /api here.
# On a single-service host the app must serve BOTH, so when a built frontend is
# present next to the app we serve it + a client-side-routing fallback. Declared
# AFTER every /api router, so the API always wins; with no build present it falls
# back to a JSON banner (API-only / test runs for non-SPA paths).
from fastapi import Depends, Request
from fastapi.responses import FileResponse, RedirectResponse, Response
from database import get_db

STATIC_DIR = os.environ.get("STATIC_DIR") or os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "static")
_HAS_SPA = os.path.isfile(os.path.join(STATIC_DIR, "index.html"))

# The user manual is built by MkDocs into static/manual/ and served from the
# same origin, so "Open the manual" works on an air-gapped install with no
# internet and no second service to deploy.
MANUAL_URL_PREFIX = "manual"

_STATIC_EXTS = (".png", ".jpg", ".jpeg", ".gif", ".svg", ".ico", ".css",
                ".js", ".woff", ".woff2", ".ttf", ".map", ".webp", ".json", ".txt")


def resolve_static_path(full_path: str, static_dir: str):
    """Decide what a non-API URL should serve. Returns ``(kind, value)``.

    Kept separate from the route so the routing rules can be tested without a
    built frontend present — `static/` is generated, so CI has no SPA and the
    route below does not even exist there.

    kinds: ``file`` (path to send), ``redirect`` (URL), ``404``, ``spa``.
    """
    if not full_path:
        return ("spa", None)

    # Resolve strictly within static_dir — block path traversal.
    p = os.path.normpath(os.path.join(static_dir, full_path))
    if p == static_dir or p.startswith(static_dir + os.sep):
        if os.path.isfile(p):
            return ("file", p)
        # The manual is a directory of pages, not a single-page app: its links
        # point at directories ("…/sales/invoices/"), so a folder has to resolve
        # to the index.html inside it the way a static web server would. Without
        # this, every manual link falls through to the SPA shell and renders the
        # ERP instead of the page.
        if os.path.isdir(p) and os.path.isfile(os.path.join(p, "index.html")):
            # Trailing slash first: the manual's links are relative, so serving
            # /manual as if it were /manual/ resolves every one of them one
            # level too high.
            if not full_path.endswith("/"):
                return ("redirect", f"/{full_path}/")
            return ("file", os.path.join(p, "index.html"))

    # Anything under /manual/ that does not exist is a genuine 404. It must not
    # return the SPA shell: the UI probes this path to decide whether to offer
    # the manual at all, and a 200 shell would make a build without the manual
    # look like it had one.
    if full_path.split("/")[0] == MANUAL_URL_PREFIX:
        return ("404", None)
    if any(full_path.endswith(e) for e in _STATIC_EXTS):
        return ("404", None)
    return ("spa", None)


SHARE_URL_PREFIX = "d"


def _esc(v) -> str:
    return (str(v or "").replace("&", "&amp;").replace("<", "&lt;")
            .replace(">", "&gt;").replace('"', "&quot;"))


def build_share_head(preview: dict | None, origin: str, has_logo: bool) -> str:
    """The <meta> block a chat app reads when a customer is sent a share link.

    WhatsApp's crawler does not run JavaScript, so nothing React renders can
    reach it — these tags have to be in the HTML the server returns or the link
    arrives as a bare URL with no card at all.

    What the card says is a privacy decision, not a marketing one. It names the
    document and who issued it and stops there: previews surface in chat lists
    and on locked phones, so an amount or a balance would be shown to whoever
    picks up the handset. Anyone who actually opens the link sees everything;
    the person glancing at a notification does not.

    `og:image` is the TENANT's logo, absolute because a crawler has no base URL,
    and omitted entirely when they have none — falling back to the vendor mark
    would put Quilit's branding in the customer's chat over their supplier's
    invoice. `twitter:card=summary` asks for the small square crop a logo
    survives, rather than the wide banner a photo wants.
    """
    if preview:
        number = _esc(preview.get("number"))
        label = _esc(preview.get("label")) or "Document"
        company = _esc(preview.get("company"))
        title = " ".join(x for x in (label, number) if x)
        if company:
            title = f"{title} — {company}"
        desc = f"Tap to view your {label.lower()}."
    else:
        # An invalid, revoked or expired token gets a card that reveals nothing
        # — including whether it was ever a real link.
        title, desc = "Shared document", "This link is no longer available."

    tags = [
        f'<meta property="og:title" content="{title}">',
        f'<meta property="og:description" content="{desc}">',
        '<meta property="og:type" content="website">',
        f'<meta name="description" content="{desc}">',
        f'<title>{title}</title>',
    ]
    if preview and has_logo:
        tags += [
            f'<meta property="og:image" content="{_esc(origin)}/api/settings/logo">',
            '<meta name="twitter:card" content="summary">',
        ]
    else:
        tags.append('<meta name="twitter:card" content="summary">')
    return "\n    ".join(tags)


def inject_share_head(html: str, head: str) -> str:
    """Put the card's tags in, and take the app's own <title> out.

    The shell ships a <title>; leaving it would give the document two, and a
    crawler that picks the first one would caption a customer's invoice
    "ERP System".
    """
    import re
    html = re.sub(r"<title>.*?</title>", "", html, count=1, flags=re.S)
    return html.replace("<head>", "<head>\n    " + head, 1)


if _HAS_SPA:
    _NO_CACHE = {"Cache-Control": "no-store, no-cache, must-revalidate",
                 "Pragma": "no-cache", "Expires": "0"}

    # Registered BEFORE the catch-all so it wins, and separate from it so the
    # database is touched only by share links — putting a DB dependency on the
    # catch-all would open a connection for every image and script tag.
    #
    # HEAD as well as GET for the same reason the catch-all takes it, plus one
    # of its own: some link scanners HEAD a URL before fetching it.
    @app.api_route("/" + SHARE_URL_PREFIX + "/{rest:path}",
                   methods=["GET", "HEAD"])
    def serve_share_page(rest: str, request: Request,
                         db=Depends(get_db)):
        from routers.communications import share_preview
        from routers.settings import _stored_logo

        # /d/<number>/<token> and the older /d/<token>: the token is the last
        # segment either way, and the number ahead of it is cosmetic.
        token = (rest or "").strip("/").split("/")[-1]
        preview = None
        has_logo = False
        try:
            preview = share_preview(db, token)
            has_logo = bool(preview) and _stored_logo(db) is not None
        except Exception:
            # A preview is decoration. If anything here fails the customer must
            # still get the page — the card is what degrades, not the document.
            preview = None

        origin = str(request.base_url).rstrip("/")
        with open(os.path.join(STATIC_DIR, "index.html"),
                  encoding="utf-8") as fh:
            shell = fh.read()
        html = inject_share_head(shell, build_share_head(preview, origin, has_logo))
        return Response(html, media_type="text/html", headers=_NO_CACHE)

    # HEAD as well as GET: this is the app's static file server, and a static
    # server that 405s a HEAD is broken. FastAPI does not add HEAD to a GET
    # route the way plain Starlette does, so it has to be asked for. The UI's
    # "is the manual here?" probe uses HEAD precisely so it doesn't download the
    # file — with GET only it got a 405 and quietly hid the button.
    @app.api_route("/{full_path:path}", methods=["GET", "HEAD"])
    def serve_spa(full_path: str = ""):
        # Unknown /api/* paths return 404 JSON, never the SPA shell.
        if full_path.startswith("api/"):
            return Response('{"detail":"Not found"}', status_code=404,
                            media_type="application/json")
        kind, value = resolve_static_path(full_path, STATIC_DIR)
        if kind == "file":
            hdrs = {"Cache-Control": "public, max-age=31536000, immutable"} \
                   if "/assets/" in full_path else {}
            return FileResponse(value, headers=hdrs)
        if kind == "redirect":
            return RedirectResponse(value, status_code=308)
        if kind == "404":
            return Response(status_code=404)
        return FileResponse(os.path.join(STATIC_DIR, "index.html"), headers=_NO_CACHE)
else:
    @app.get("/")
    def root():
        return {"message": "ERP System API v2.0"}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run("main:app", host="0.0.0.0",
                port=int(os.environ.get("PORT", 8000)), reload=True)
