"""
Error reporting and support inbox — every tenant's problems in one place.

Reports live in the SHARED `public` schema, not inside the tenant that raised
them. The Control Center has to answer "what is broken across all customers?"
in one query; if each report sat in its own tenant schema that would mean
connecting to every schema in turn, which does not scale past a handful of
customers and makes cross-tenant triage impossible.

A report is deliberately cheap to file: the ERP captures the technical context
(error, stack, page, browser, user, tenant, timestamp) automatically, and the
user only has to say what they were trying to do. Anything that asks a
frustrated user to describe a stack trace does not get filed.

Reports are never deleted from the UI — status moves open -> investigating ->
resolved, so the history of what broke for whom is preserved.
"""
import json

STATUSES   = ("open", "investigating", "resolved")
SEVERITIES = ("low", "medium", "high", "critical")

# Free-text fields are truncated on write. A runaway stack trace or a pasted
# console dump should not be able to bloat the shared catalog.
_MAX_MESSAGE = 4000
_MAX_STACK   = 16000
_MAX_TEXT    = 2000


def _clip(value, limit):
    if value is None:
        return None
    text = str(value)
    return text if len(text) <= limit else text[:limit] + "\n… [truncated]"


def ensure_reports_catalog(raw) -> None:
    with raw.cursor() as cur:
        cur.execute("""
            CREATE TABLE IF NOT EXISTS public.error_reports (
                id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                tenant_slug  TEXT,
                tenant_name  TEXT,
                severity     TEXT NOT NULL DEFAULT 'medium',
                status       TEXT NOT NULL DEFAULT 'open',
                title        TEXT NOT NULL,
                message      TEXT,
                stack        TEXT,
                page_url     TEXT,
                user_agent   TEXT,
                app_version  TEXT,
                user_id      INTEGER,
                username     TEXT,
                description  TEXT,
                assignee     TEXT,
                notes        TEXT,
                created_at   TEXT NOT NULL,
                updated_at   TEXT,
                resolved_at  TEXT
            )
        """)
        # The inbox is almost always filtered by status or scoped to one
        # customer, and always ordered newest-first.
        cur.execute("CREATE INDEX IF NOT EXISTS idx_reports_status "
                    "ON public.error_reports(status, created_at DESC)")
        cur.execute("CREATE INDEX IF NOT EXISTS idx_reports_tenant "
                    "ON public.error_reports(tenant_slug, created_at DESC)")
    raw.commit()


def _connect():
    from tenancy import _connect as tenancy_connect
    return tenancy_connect()


def file_report(payload: dict, *, tenant_slug=None, tenant_name=None,
                user_id=None, username=None) -> dict:
    """Record a problem report. Returns {id, status}.

    Identity and tenancy are taken from the authenticated session, never from
    the request body — a user must not be able to file a report against
    another customer.
    """
    from utils import _now
    severity = (payload.get("severity") or "medium").lower()
    if severity not in SEVERITIES:
        severity = "medium"

    title = _clip(payload.get("title") or "Problem report", 300)
    raw = _connect()
    try:
        ensure_reports_catalog(raw)
        with raw.cursor() as cur:
            cur.execute(
                "INSERT INTO public.error_reports "
                "(tenant_slug, tenant_name, severity, status, title, message, stack, "
                " page_url, user_agent, app_version, user_id, username, description, "
                " created_at) "
                "VALUES (%s,%s,%s,'open',%s,%s,%s,%s,%s,%s,%s,%s,%s,%s) RETURNING id",
                (tenant_slug, tenant_name, severity, title,
                 _clip(payload.get("message"), _MAX_MESSAGE),
                 _clip(payload.get("stack"), _MAX_STACK),
                 _clip(payload.get("page_url"), 500),
                 _clip(payload.get("user_agent"), 500),
                 _clip(payload.get("app_version"), 60),
                 user_id, username,
                 _clip(payload.get("description"), _MAX_TEXT),
                 _now()))
            new_id = cur.fetchone()["id"]
        raw.commit()
    finally:
        raw.close()
    return {"id": new_id, "status": "open"}


def list_reports(status=None, tenant_slug=None, severity=None, q=None,
                 limit=100, offset=0) -> dict:
    """Inbox query: filter by status / customer / severity / free text."""
    where, params = [], []
    if status in STATUSES:
        where.append("status = %s"); params.append(status)
    if tenant_slug:
        where.append("tenant_slug = %s"); params.append(tenant_slug)
    if severity in SEVERITIES:
        where.append("severity = %s"); params.append(severity)
    if q:
        where.append("(title ILIKE %s OR message ILIKE %s OR description ILIKE %s "
                     "OR username ILIKE %s)")
        params += [f"%{q}%"] * 4
    clause = (" WHERE " + " AND ".join(where)) if where else ""
    limit = max(1, min(int(limit or 100), 500))

    raw = _connect()
    try:
        ensure_reports_catalog(raw)
        with raw.cursor() as cur:
            cur.execute(f"SELECT COUNT(*) AS n FROM public.error_reports{clause}", params)
            total = cur.fetchone()["n"]
            cur.execute(
                f"SELECT * FROM public.error_reports{clause} "
                "ORDER BY created_at DESC, id DESC LIMIT %s OFFSET %s",
                params + [limit, int(offset or 0)])
            rows = [dict(r) for r in cur.fetchall()]
            # Counts per status drive the inbox badges without a second query.
            cur.execute("SELECT status, COUNT(*) AS n FROM public.error_reports "
                        "GROUP BY status")
            counts = {r["status"]: r["n"] for r in cur.fetchall()}
    finally:
        raw.close()
    return {"items": rows, "total": total, "limit": limit,
            "offset": int(offset or 0), "counts": counts}


def update_report(report_id: int, changes: dict) -> dict:
    """Triage a report: status, severity, assignee, notes."""
    from utils import _now
    sets, params = [], []
    if "status" in changes and changes["status"] in STATUSES:
        sets.append("status = %s"); params.append(changes["status"])
        if changes["status"] == "resolved":
            sets.append("resolved_at = %s"); params.append(_now())
    if "severity" in changes and changes["severity"] in SEVERITIES:
        sets.append("severity = %s"); params.append(changes["severity"])
    for field, limit in (("assignee", 120), ("notes", _MAX_TEXT)):
        if field in changes:
            sets.append(f"{field} = %s"); params.append(_clip(changes[field], limit))
    if not sets:
        raise ValueError("Nothing to update.")
    sets.append("updated_at = %s"); params.append(_now())
    params.append(int(report_id))

    raw = _connect()
    try:
        ensure_reports_catalog(raw)
        with raw.cursor() as cur:
            cur.execute(f"UPDATE public.error_reports SET {', '.join(sets)} "
                        "WHERE id = %s RETURNING *", params)
            row = cur.fetchone()
            if not row:
                raise ValueError(f"No such report: {report_id}")
        raw.commit()
    finally:
        raw.close()
    return dict(row)


def report_stats() -> dict:
    """Per-tenant error counts — the signal for 'which customer needs help?'."""
    raw = _connect()
    try:
        ensure_reports_catalog(raw)
        with raw.cursor() as cur:
            cur.execute(
                "SELECT tenant_slug, "
                "       COUNT(*) AS total, "
                "       COUNT(*) FILTER (WHERE status = 'open') AS open, "
                "       COUNT(*) FILTER (WHERE severity IN ('high','critical') "
                "                        AND status <> 'resolved') AS urgent, "
                "       MAX(created_at) AS last_report "
                "FROM public.error_reports GROUP BY tenant_slug")
            return {r["tenant_slug"]: dict(r) for r in cur.fetchall()}
    finally:
        raw.close()
