"""
Schema-per-tenant multi-tenancy (Phase 2 — docs/SAAS_ARCHITECTURE.md §7).

Each company is an isolated PostgreSQL *schema* (``tenant_<slug>``) that contains
a full copy of the ERP — including its own users / roles / permissions / audit
(ADR-3). Isolation is structural: a query in one schema cannot see another's
tables. The only shared object is the ``public.tenants`` catalog.

How a request finds its tenant:
  * Authenticated requests carry the schema in the signed JWT (``schema`` claim),
    so a token minted for tenant A can only ever reach tenant A — even if its
    user-id collides with a user in tenant B.
  * Login / unauthenticated requests resolve the tenant from the ``X-Tenant``
    header or the host subdomain, looked up in ``public.tenants``.

``TenantMiddleware`` (pure ASGI) stashes the resolved schema in a ContextVar;
``database.get_db`` reads it and pins the connection's ``search_path``. None of
the routers change. In single-tenant mode (``TENANCY=single``, the default) the
middleware is inert and everything behaves exactly as before.
"""
import re
from http.cookies import SimpleCookie

import jwt

from auth_utils import SECRET_KEY, ALGORITHM, COOKIE_NAME, hash_password, verify_password
from tenant_context import (
    IS_SCHEMA_TENANCY, valid_schema_name,
    set_current_schema, reset_current_schema,
)


def _gen_password(n: int = 16) -> str:
    import secrets
    import string
    alphabet = string.ascii_letters + string.digits + "!@#$%^&*"
    return "".join(secrets.choice(alphabet) for _ in range(n))

# slug → schema. Slugs are lower-case alnum/underscore so the derived schema name
# is always a safe identifier.
_SLUG_RE = re.compile(r"^[a-z0-9][a-z0-9_]{0,40}$")


def schema_for_slug(slug: str) -> str:
    return "tenant_" + slug


def valid_slug(slug) -> bool:
    return isinstance(slug, str) and bool(_SLUG_RE.match(slug))


# ── tenant catalog (lives in public) ─────────────────────────────────────────

def _connect():
    import psycopg
    from psycopg.rows import dict_row
    from database import _pg_dsn
    return psycopg.connect(_pg_dsn(), row_factory=dict_row)


# Provisioning profile carried per tenant. Kept in the shared public catalog
# (not inside the tenant schema) because the Control Center has to read across
# every customer without connecting to each schema in turn.
#
# `modules` stores the SELECTED set only. The effective set is always the
# dependency closure of this, computed at read time by capabilities.resolve(),
# so a plan can never be stored in a state that does not work.
_TENANT_COLUMNS = (
    "industry        TEXT",
    "language        TEXT DEFAULT 'en'",
    "currency        TEXT DEFAULT 'USD'",
    "contact_email   TEXT",
    "contact_phone   TEXT",
    "company_address TEXT",
    "tax_number      TEXT",
    "modules         TEXT",          # comma-separated selected module keys
    "max_users       INTEGER",       # licensed seats; NULL = unlimited
    "trial_ends_at   TEXT",          # ISO date; NULL = not a trial
    "license_expires_at TEXT",       # ISO date; NULL = perpetual
    "notes           TEXT",
    "updated_at      TEXT",
)


def ensure_tenants_catalog(raw) -> None:
    with raw.cursor() as cur:
        cur.execute("""
            CREATE TABLE IF NOT EXISTS public.tenants (
                id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                slug        TEXT UNIQUE NOT NULL,
                schema_name TEXT UNIQUE NOT NULL,
                name        TEXT,
                status      TEXT NOT NULL DEFAULT 'active',   -- 'active' | 'suspended'
                plan        TEXT NOT NULL DEFAULT 'standard',
                created_at  TEXT NOT NULL
            )
        """)
        # Additive migration. New installs get these from the CREATE above on
        # the next release; existing catalogs are upgraded in place. ADD COLUMN
        # IF NOT EXISTS keeps this idempotent, so it runs safely on every boot.
        for ddl in _TENANT_COLUMNS:
            cur.execute(f"ALTER TABLE public.tenants ADD COLUMN IF NOT EXISTS {ddl}")
    raw.commit()


def _schema_initialized(raw, schema: str) -> bool:
    with raw.cursor() as cur:
        cur.execute("SELECT to_regclass(%s) AS reg", (f"{schema}.schema_migrations",))
        if cur.fetchone()["reg"] is None:
            return False
        cur.execute(f'SELECT count(*) AS n FROM "{schema}".schema_migrations')
        return cur.fetchone()["n"] > 0


def provision_tenant(slug: str, name: str = None, plan: str = "standard",
                     admin_password: str = None, profile: dict = None) -> dict:
    """Create and seed a new tenant schema, and register it in the catalog.

    Idempotent on the schema/catalog, but each call resets the tenant admin's
    password to a freshly generated (or supplied) value and returns it ONCE so the
    operator can hand the new customer their first login. Returns the catalog row
    plus ``admin_username`` / ``admin_password``.
    """
    from utils import _now
    from db_compat import CompatConn
    from dialect import get_dialect
    from database import (_apply_pg_baseline, _ensure_pg_post_baseline,
                          _seed_roles_and_admin)

    if not valid_slug(slug):
        raise ValueError(f"Invalid tenant slug: {slug!r} (use a-z, 0-9, _).")
    schema = schema_for_slug(slug)
    admin_password = admin_password or _gen_password()

    raw = _connect()
    try:
        ensure_tenants_catalog(raw)
        with raw.cursor() as cur:
            cur.execute(f'CREATE SCHEMA IF NOT EXISTS "{schema}"')
        raw.commit()

        # Point the session at the new schema so the baseline's unqualified DDL
        # and the shared seeding land inside it (not public).
        with raw.cursor() as cur:
            cur.execute(f'SET search_path TO "{schema}", public')
        if not _schema_initialized(raw, schema):
            _apply_pg_baseline(raw)                 # tables/indexes/ledger → tenant schema
        # The baseline is a SQUASHED snapshot; every migration added after it
        # was generated still has to run. _init_db_postgres does both steps —
        # provisioning previously did only the first, so each tenant schema was
        # born missing every later column (branch_id and friends) and every
        # query touching one returned a 500. Idempotent, so it is also the
        # upgrade path for schemas provisioned before this fix.
        _ensure_pg_post_baseline(raw)
        conn = CompatConn(raw, get_dialect("postgres"))
        _seed_roles_and_admin(conn)                 # roles/permissions/admin → tenant schema
        # Set a known initial admin password (the seeding's own random one is never
        # surfaced); force a reset on first login.
        conn.execute("UPDATE users SET password_hash=?, must_change_password=1 "
                     "WHERE username='admin'", (hash_password(admin_password),))
        conn.commit()

        with raw.cursor() as cur:
            cur.execute(
                "INSERT INTO public.tenants (slug, schema_name, name, status, plan, created_at) "
                "VALUES (%s, %s, %s, 'active', %s, %s) ON CONFLICT (slug) DO NOTHING",
                (slug, schema, name or slug, plan, _now()))
            # Profile fields are written separately so provisioning stays
            # backward compatible: an older caller that passes no profile
            # provisions exactly as before.
            if profile:
                _apply_profile(cur, slug, profile)
            cur.execute("SELECT * FROM public.tenants WHERE slug=%s", (slug,))
            row = cur.fetchone()
        raw.commit()
    finally:
        raw.close()

    _CACHE.pop(slug, None)               # refresh any cached lookup
    _SCHEMA_STATUS.pop(schema, None)
    _MODULES_CACHE.pop(schema, None)
    return {**dict(row), "admin_username": "admin", "admin_password": admin_password}


# Fields the Control Center may write. Anything not listed is ignored rather
# than rejected, so an older console posting an unknown key cannot 500 a
# provisioning run.
_PROFILE_FIELDS = (
    "name", "plan", "industry", "language", "currency", "contact_email",
    "contact_phone", "company_address", "tax_number", "max_users",
    "trial_ends_at", "license_expires_at", "notes",
)


def _apply_profile(cur, slug: str, profile: dict) -> None:
    """UPDATE the catalog row from a profile dict. Caller owns the transaction."""
    # `_now` is imported per-function throughout this module (utils imports
    # database, so a module-level import would create a cycle).
    from utils import _now
    sets, params = [], []
    for field in _PROFILE_FIELDS:
        if field in profile and profile[field] is not None:
            sets.append(f"{field} = %s")
            params.append(profile[field])
    # `modules` is normalised: store the SELECTED keys, deduplicated and
    # ordered, so the row is stable and diffable. The effective set is always
    # recomputed from this by capabilities.resolve().
    if "modules" in profile and profile["modules"] is not None:
        import capabilities
        selected = sorted({m.strip() for m in profile["modules"] if str(m).strip()
                           and capabilities.known_module(str(m).strip())})
        sets.append("modules = %s")
        params.append(",".join(selected))
    if not sets:
        return
    sets.append("updated_at = %s")
    params.append(_now())
    params.append(slug)
    cur.execute(f"UPDATE public.tenants SET {', '.join(sets)} WHERE slug = %s", params)


def update_tenant(slug: str, profile: dict) -> dict:
    """Edit a tenant's provisioning profile. Returns the updated catalog row."""
    if not valid_slug(slug):
        raise ValueError(f"Invalid tenant slug: {slug!r}")
    raw = _connect()
    try:
        ensure_tenants_catalog(raw)
        with raw.cursor() as cur:
            _apply_profile(cur, slug, profile)
            cur.execute("SELECT * FROM public.tenants WHERE slug=%s", (slug,))
            row = cur.fetchone()
        raw.commit()
    finally:
        raw.close()
    _CACHE.pop(slug, None)
    _MODULES_CACHE.pop(slug, None)
    return dict(row) if row else None


def delete_tenant(slug: str) -> dict:
    """Permanently decommission a tenant: drop its schema and forget it.

    IRREVERSIBLE. Everything the customer owns lives in their schema, so this
    destroys their ledger, documents metadata, users and audit trail with no
    undo. Suspending (`set_tenant_status`) is almost always what you want -
    it blocks access, keeps the data, and can be reversed by flipping the
    status back. Delete is for decommissioning a cancelled or mistaken
    tenant, and the API requires an explicit confirmation to reach it.

    Returns a summary of what was removed.
    """
    if not valid_slug(slug):
        raise ValueError(f"Invalid tenant slug: {slug!r}")
    schema = schema_for_slug(slug)
    # Defence in depth: schema_for_slug is the only source of this identifier
    # and valid_slug has already constrained it, but the name is interpolated
    # into DDL (it cannot be a bind parameter), so re-check before use.
    if not valid_schema_name(schema):
        raise ValueError(f"Refusing to drop unsafe schema name: {schema!r}")

    raw = _connect()
    try:
        ensure_tenants_catalog(raw)
        ensure_tenant_domains_catalog(raw)
        with raw.cursor() as cur:
            cur.execute("SELECT slug, name FROM public.tenants WHERE slug=%s", (slug,))
            row = cur.fetchone()
            if not row:
                raise ValueError(f"No such tenant: {slug!r}")
            cur.execute(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE')
            cur.execute("DELETE FROM public.tenant_domains WHERE slug=%s", (slug,))
            domains_removed = cur.rowcount or 0
            cur.execute("DELETE FROM public.tenants WHERE slug=%s", (slug,))
        raw.commit()
    finally:
        raw.close()

    _CACHE.pop(slug, None)
    _SCHEMA_STATUS.pop(schema, None)
    _MODULES_CACHE.pop(schema, None)
    _HOST_CACHE.clear()                  # any domain pointing here is now gone
    return {"slug": slug, "name": row.get("name"), "schema": schema,
            "domains_removed": domains_removed, "deleted": True}


def tenant_modules(schema: str):
    """Effective (dependency-closed) module set for a schema, or None when the
    tenant has no explicit licence and should see everything.

    Cached: this is consulted on every permission check, so an uncached lookup
    would put a query in front of every request.
    """
    if schema in _MODULES_CACHE:
        return _MODULES_CACHE[schema]
    try:
        raw = _connect()
    except Exception:
        return None                      # fail open rather than lock everyone out
    try:
        with raw.cursor() as cur:
            cur.execute("SELECT modules FROM public.tenants WHERE schema_name=%s",
                        (schema,))
            row = cur.fetchone()
    except Exception:
        return None
    finally:
        raw.close()
    raw_modules = (row or {}).get("modules") if row else None
    if not raw_modules:
        result = None                    # unlicensed == unrestricted (dev/demo)
    else:
        import capabilities
        result = capabilities.resolve(
            {m.strip() for m in raw_modules.split(",") if m.strip()})
    _MODULES_CACHE[schema] = result
    return result


def list_tenants() -> list:
    raw = _connect()
    try:
        ensure_tenants_catalog(raw)
        with raw.cursor() as cur:
            cur.execute("SELECT * FROM public.tenants ORDER BY id")
            return [dict(r) for r in cur.fetchall()]
    finally:
        raw.close()


def set_tenant_status(slug: str, status: str) -> None:
    if status not in ("active", "suspended"):
        raise ValueError("status must be 'active' or 'suspended'")
    raw = _connect()
    try:
        with raw.cursor() as cur:
            cur.execute("UPDATE public.tenants SET status=%s WHERE slug=%s", (status, slug))
        raw.commit()
    finally:
        raw.close()
    _CACHE.pop(slug, None)
    _SCHEMA_STATUS.clear()
    _HOST_CACHE.clear()


# ── custom domains (each tenant on its own hostname) ─────────────────────────
# A tenant is normally reached at <slug>.<vendor-domain> (the host subdomain). To
# let a client use their OWN domain (erp.clientco.com), we map full hostnames to
# tenant schemas in public.tenant_domains. Ownership is proved with a DNS TXT
# record BEFORE the domain routes anywhere (so verification never depends on the
# domain already pointing at us, and a cert is only ever issued for a verified
# host). Resolution then matches the exact Host header to a verified domain.

# RFC-1123-ish hostname check (lower-case, dotted, no leading/trailing hyphen).
_DOMAIN_RE = re.compile(
    r"^(?=.{1,253}$)(?!-)[a-z0-9-]{1,63}(?<!-)(\.(?!-)[a-z0-9-]{1,63}(?<!-))+$"
)
# Where the client publishes the ownership token: _erp-verify.<domain> TXT "<token>".
VERIFY_TXT_PREFIX = "_erp-verify"


def valid_domain(d) -> bool:
    return isinstance(d, str) and bool(_DOMAIN_RE.match(d.strip().lower().rstrip(".")))


def ensure_tenant_domains_catalog(raw) -> None:
    with raw.cursor() as cur:
        cur.execute("""
            CREATE TABLE IF NOT EXISTS public.tenant_domains (
                id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                domain       TEXT UNIQUE NOT NULL,
                schema_name  TEXT NOT NULL,
                slug         TEXT NOT NULL,
                verified     INTEGER NOT NULL DEFAULT 0,
                verify_token TEXT NOT NULL,
                created_at   TEXT NOT NULL,
                verified_at  TEXT
            )
        """)
    raw.commit()


def _resolve_txt(name: str) -> list:
    """Return the TXT record strings for `name`, or [] on any failure. Isolated
    into its own function so tests can monkeypatch it without real DNS. Uses
    dnspython when available; a missing library simply means 'cannot verify yet'."""
    try:
        import dns.resolver
    except Exception:
        return []
    try:
        answers = dns.resolver.resolve(name, "TXT")
    except Exception:
        return []
    out = []
    for r in answers:
        try:
            out.append(b"".join(getattr(r, "strings", [])).decode("utf-8", "ignore"))
        except Exception:
            out.append(r.to_text().strip('"'))
    return [s for s in out if s]


def add_tenant_domain(slug: str, domain: str) -> dict:
    """Attach a custom domain to a tenant (pending verification). Idempotent on
    the domain; re-adding keeps the existing token. Returns the row plus the TXT
    record the client must publish to prove ownership."""
    from utils import _now
    import secrets
    domain = (domain or "").strip().lower().rstrip(".")
    if not valid_domain(domain):
        raise ValueError(f"Invalid domain: {domain!r}")
    if not valid_slug(slug):
        raise ValueError(f"Invalid tenant slug: {slug!r}")
    schema = schema_for_slug(slug)
    raw = _connect()
    try:
        ensure_tenants_catalog(raw)
        ensure_tenant_domains_catalog(raw)
        with raw.cursor() as cur:
            cur.execute("SELECT 1 FROM public.tenants WHERE slug=%s", (slug,))
            if not cur.fetchone():
                raise ValueError(f"No such tenant: {slug!r}")
            # A domain belongs to exactly one tenant.
            cur.execute("SELECT slug FROM public.tenant_domains WHERE domain=%s", (domain,))
            existing = cur.fetchone()
            if existing and existing["slug"] != slug:
                raise ValueError(f"Domain {domain!r} is already attached to another tenant.")
            token = secrets.token_hex(16)
            cur.execute(
                "INSERT INTO public.tenant_domains (domain, schema_name, slug, verify_token, created_at) "
                "VALUES (%s, %s, %s, %s, %s) ON CONFLICT (domain) DO NOTHING",
                (domain, schema, slug, token, _now()))
            cur.execute("SELECT * FROM public.tenant_domains WHERE domain=%s", (domain,))
            row = cur.fetchone()
        raw.commit()
    finally:
        raw.close()
    _HOST_CACHE.pop(domain, None)
    return {
        **dict(row),
        "txt_name":  f"{VERIFY_TXT_PREFIX}.{domain}",
        "txt_value": row["verify_token"],
    }


def list_tenant_domains(slug: str = None) -> list:
    raw = _connect()
    try:
        ensure_tenant_domains_catalog(raw)
        with raw.cursor() as cur:
            if slug:
                cur.execute("SELECT * FROM public.tenant_domains WHERE slug=%s ORDER BY id", (slug,))
            else:
                cur.execute("SELECT * FROM public.tenant_domains ORDER BY id")
            return [dict(r) for r in cur.fetchall()]
    finally:
        raw.close()


def remove_tenant_domain(domain: str) -> None:
    domain = (domain or "").strip().lower().rstrip(".")
    raw = _connect()
    try:
        with raw.cursor() as cur:
            cur.execute("DELETE FROM public.tenant_domains WHERE domain=%s", (domain,))
        raw.commit()
    finally:
        raw.close()
    _HOST_CACHE.pop(domain, None)


def verify_tenant_domain(domain: str) -> dict:
    """Check the DNS TXT record and mark the domain verified if the token matches.
    Returns {domain, verified}."""
    from utils import _now
    domain = (domain or "").strip().lower().rstrip(".")
    raw = _connect()
    try:
        ensure_tenant_domains_catalog(raw)
        with raw.cursor() as cur:
            cur.execute("SELECT verify_token FROM public.tenant_domains WHERE domain=%s", (domain,))
            row = cur.fetchone()
            if not row:
                raise ValueError(f"Domain not found: {domain!r}")
            token = row["verify_token"]
            txt = _resolve_txt(f"{VERIFY_TXT_PREFIX}.{domain}")
            ok = any(token == t.strip() for t in txt)
            if ok:
                cur.execute(
                    "UPDATE public.tenant_domains SET verified=1, verified_at=%s WHERE domain=%s",
                    (_now(), domain))
        raw.commit()
    finally:
        raw.close()
    _HOST_CACHE.pop(domain, None)
    return {"domain": domain, "verified": bool(ok)}


def is_verified_domain(host: str) -> bool:
    """True if `host` is a known, verified tenant domain. Used by the on-demand
    TLS gate so a certificate is only ever issued for a host we recognise."""
    host = (host or "").strip().lower().rstrip(".")
    if not host:
        return False
    return _lookup_by_host(host) is not None


# ── platform-operator (SaaS vendor) accounts ─────────────────────────────────
# A separate identity tier from tenant users, living in public.platform_admins.
# Operators provision/suspend tenants; they never appear in any tenant schema.

def ensure_platform_admins_catalog(raw) -> None:
    with raw.cursor() as cur:
        cur.execute("""
            CREATE TABLE IF NOT EXISTS public.platform_admins (
                id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username      TEXT UNIQUE NOT NULL,
                password_hash TEXT NOT NULL,
                full_name     TEXT,
                is_active     INTEGER NOT NULL DEFAULT 1,
                created_at    TEXT NOT NULL,
                last_login    TEXT
            )
        """)
    raw.commit()


def create_platform_admin(username: str, password: str = None, full_name: str = None) -> dict:
    """Create a platform operator (or reset its password). Returns
    {username, password}; the password is surfaced exactly once."""
    from utils import _now
    password = password or _gen_password()
    raw = _connect()
    try:
        ensure_platform_admins_catalog(raw)
        with raw.cursor() as cur:
            cur.execute(
                "INSERT INTO public.platform_admins (username, password_hash, full_name, created_at) "
                "VALUES (%s, %s, %s, %s) "
                "ON CONFLICT (username) DO UPDATE SET password_hash = EXCLUDED.password_hash",
                (username, hash_password(password), full_name or username, _now()))
        raw.commit()
    finally:
        raw.close()
    return {"username": username, "password": password}


def verify_platform_admin(username: str, password: str):
    raw = _connect()
    try:
        ensure_platform_admins_catalog(raw)
        with raw.cursor() as cur:
            cur.execute("SELECT * FROM public.platform_admins WHERE username=%s", (username,))
            row = cur.fetchone()
    finally:
        raw.close()
    if not row or not row["is_active"] or not verify_password(password, row["password_hash"]):
        return None
    return dict(row)


def get_platform_admin(admin_id: int):
    raw = _connect()
    try:
        with raw.cursor() as cur:
            cur.execute("SELECT * FROM public.platform_admins WHERE id=%s", (admin_id,))
            row = cur.fetchone()
    except Exception:
        return None
    finally:
        raw.close()
    return dict(row) if row else None


# ── resolution (cached) ──────────────────────────────────────────────────────
# Small in-process caches. Cleared on provision / status change. A production
# deployment would back these with Redis (Phase 4); for now a lookup miss does a
# short-lived connection.
_CACHE = {}            # slug -> (schema, status)
_SCHEMA_STATUS = {}    # schema -> status
_HOST_CACHE = {}       # custom domain (host) -> (schema, status)
_MODULES_CACHE = {}    # schema -> effective module set (or None)


def _lookup_by_slug(slug: str):
    if slug in _CACHE:
        return _CACHE[slug]
    try:
        raw = _connect()
    except Exception:
        return None
    try:
        with raw.cursor() as cur:
            cur.execute("SELECT schema_name, status FROM public.tenants WHERE slug=%s", (slug,))
            row = cur.fetchone()
    except Exception:
        return None
    finally:
        raw.close()
    if not row:
        return None
    res = (row["schema_name"], row["status"])
    _CACHE[slug] = res
    _SCHEMA_STATUS[row["schema_name"]] = row["status"]
    return res


def _lookup_by_host(host: str):
    """Resolve a full hostname (custom domain) to ``(schema, status)`` via the
    verified entries in public.tenant_domains, or None. Cached."""
    if host in _HOST_CACHE:
        return _HOST_CACHE[host]
    try:
        raw = _connect()
    except Exception:
        return None
    try:
        with raw.cursor() as cur:
            cur.execute(
                "SELECT t.schema_name, t.status "
                "FROM public.tenant_domains d "
                "JOIN public.tenants t ON t.schema_name = d.schema_name "
                "WHERE d.domain = %s AND d.verified = 1",
                (host,))
            row = cur.fetchone()
    except Exception:
        return None
    finally:
        raw.close()
    if not row:
        return None
    res = (row["schema_name"], row["status"])
    _HOST_CACHE[host] = res
    return res


def _schema_status(schema: str):
    """Return the tenant status ('active' | 'suspended') for a schema, or None if
    no such tenant exists. Cached."""
    if schema in _SCHEMA_STATUS:
        return _SCHEMA_STATUS[schema]
    try:
        raw = _connect()
    except Exception:
        return None
    try:
        with raw.cursor() as cur:
            cur.execute("SELECT status FROM public.tenants WHERE schema_name=%s", (schema,))
            row = cur.fetchone()
    except Exception:
        return None
    finally:
        raw.close()
    if not row:
        return None
    _SCHEMA_STATUS[schema] = row["status"]
    return row["status"]


def _schema_from_cookie(cookie_header: str):
    if not cookie_header:
        return None
    jar = SimpleCookie()
    try:
        jar.load(cookie_header)
    except Exception:
        return None
    if COOKIE_NAME not in jar:
        return None
    try:
        # Signature-verified, but ignore expiry here — expiry is enforced later by
        # require_auth. We only need the (authentic) schema claim to route the DB.
        payload = jwt.decode(jar[COOKIE_NAME].value, SECRET_KEY,
                             algorithms=[ALGORITHM], options={"verify_exp": False})
    except Exception:
        return None
    schema = payload.get("schema")
    return schema if valid_schema_name(schema) else None


def _subdomain(host: str):
    parts = host.split(".")
    if len(parts) >= 3 and parts[0] not in ("www", "app", "api", "admin"):
        return parts[0]
    return None


def resolve_tenant_from_scope(scope):
    """Resolve the request's tenant. Returns ``(schema, status)`` or ``None``.
    Priority: signed JWT ``schema`` claim → ``X-Tenant`` header → host subdomain."""
    headers = {k.decode("latin1").lower(): v.decode("latin1")
               for k, v in scope.get("headers", [])}

    # 1) Authenticated request → the signed JWT's schema claim is authoritative.
    schema = _schema_from_cookie(headers.get("cookie", ""))
    if schema:
        status = _schema_status(schema)
        if status:
            return (schema, status)

    # 2) Explicit X-Tenant header (login form / API clients).
    slug = headers.get("x-tenant", "").strip().lower()
    if valid_slug(slug):
        found = _lookup_by_slug(slug)
        if found:
            return found

    host = headers.get("host", "").split(":")[0].strip().lower().rstrip(".")

    # 3) Custom domain — exact Host match against a verified tenant domain
    #    (erp.clientco.com → tenant). Checked before the subdomain scheme so a
    #    client's own domain takes precedence.
    if host:
        found = _lookup_by_host(host)
        if found:
            return found

    # 4) Host subdomain (acme.erp.app → 'acme').
    sub = _subdomain(host)
    if sub and valid_slug(sub):
        found = _lookup_by_slug(sub)
        if found:
            return found

    return None  # unresolved → get_db falls back to `public` (no business tables)


class TenantMiddleware:
    """Pure-ASGI middleware: resolve the request's tenant schema and stash it in
    the ContextVar so get_db can pin the connection's search_path. A request that
    resolves to a SUSPENDED tenant is blocked with 402. Inert unless
    TENANCY=schema."""

    def __init__(self, app):
        self.app = app

    async def __call__(self, scope, receive, send):
        if scope.get("type") != "http" or not IS_SCHEMA_TENANCY:
            await self.app(scope, receive, send)
            return
        resolved = resolve_tenant_from_scope(scope)
        if resolved is not None and resolved[1] != "active":
            from starlette.responses import JSONResponse
            await JSONResponse(
                {"detail": "This workspace is suspended. Please contact support."},
                status_code=402)(scope, receive, send)
            return
        schema = resolved[0] if resolved else None
        token = set_current_schema(schema)
        try:
            await self.app(scope, receive, send)
        finally:
            reset_current_schema(token)
