"""
Schema-per-tenant multi-tenancy (Phase 2 — docs/SAAS_ARCHITECTURE.md §7).

Each company is an isolated PostgreSQL *schema* (``tenant_<slug>``) that contains
a full copy of the ERP — including its own users / roles / permissions / audit
(ADR-3). Isolation is structural: a query in one schema cannot see another's
tables. The only shared object is the ``public.tenants`` catalog.

How a request finds its tenant:
  * Authenticated requests carry the schema in the signed JWT (``schema`` claim),
    so a token minted for tenant A can only ever reach tenant A — even if its
    user-id collides with a user in tenant B.
  * Login / unauthenticated requests resolve the tenant from the ``X-Tenant``
    header or the host subdomain, looked up in ``public.tenants``.

``TenantMiddleware`` (pure ASGI) stashes the resolved schema in a ContextVar;
``database.get_db`` reads it and pins the connection's ``search_path``. None of
the routers change. In single-tenant mode (``TENANCY=single``, the default) the
middleware is inert and everything behaves exactly as before.
"""
import re
from http.cookies import SimpleCookie

import jwt

from auth_utils import SECRET_KEY, ALGORITHM, COOKIE_NAME
from tenant_context import (
    IS_SCHEMA_TENANCY, valid_schema_name,
    set_current_schema, reset_current_schema,
)

# slug → schema. Slugs are lower-case alnum/underscore so the derived schema name
# is always a safe identifier.
_SLUG_RE = re.compile(r"^[a-z0-9][a-z0-9_]{0,40}$")


def schema_for_slug(slug: str) -> str:
    return "tenant_" + slug


def valid_slug(slug) -> bool:
    return isinstance(slug, str) and bool(_SLUG_RE.match(slug))


# ── tenant catalog (lives in public) ─────────────────────────────────────────

def _connect():
    import psycopg
    from psycopg.rows import dict_row
    from database import _pg_dsn
    return psycopg.connect(_pg_dsn(), row_factory=dict_row)


def ensure_tenants_catalog(raw) -> None:
    with raw.cursor() as cur:
        cur.execute("""
            CREATE TABLE IF NOT EXISTS public.tenants (
                id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                slug        TEXT UNIQUE NOT NULL,
                schema_name TEXT UNIQUE NOT NULL,
                name        TEXT,
                status      TEXT NOT NULL DEFAULT 'active',   -- 'active' | 'suspended'
                plan        TEXT NOT NULL DEFAULT 'standard',
                created_at  TEXT NOT NULL
            )
        """)
    raw.commit()


def _schema_initialized(raw, schema: str) -> bool:
    with raw.cursor() as cur:
        cur.execute("SELECT to_regclass(%s) AS reg", (f"{schema}.schema_migrations",))
        if cur.fetchone()["reg"] is None:
            return False
        cur.execute(f'SELECT count(*) AS n FROM "{schema}".schema_migrations')
        return cur.fetchone()["n"] > 0


def provision_tenant(slug: str, name: str = None, plan: str = "standard") -> dict:
    """Create and seed a new tenant schema, and register it in the catalog.

    Idempotent: re-provisioning an existing slug leaves it intact. Returns the
    catalog row as a dict.
    """
    from utils import _now
    from db_compat import CompatConn
    from dialect import get_dialect
    from database import _apply_pg_baseline, _seed_roles_and_admin

    if not valid_slug(slug):
        raise ValueError(f"Invalid tenant slug: {slug!r} (use a-z, 0-9, _).")
    schema = schema_for_slug(slug)

    raw = _connect()
    try:
        ensure_tenants_catalog(raw)
        with raw.cursor() as cur:
            cur.execute(f'CREATE SCHEMA IF NOT EXISTS "{schema}"')
        raw.commit()

        # Point the session at the new schema so the baseline's unqualified DDL
        # and the shared seeding land inside it (not public).
        with raw.cursor() as cur:
            cur.execute(f'SET search_path TO "{schema}", public')
        if not _schema_initialized(raw, schema):
            _apply_pg_baseline(raw)                 # tables/indexes/ledger → tenant schema
        conn = CompatConn(raw, get_dialect("postgres"))
        _seed_roles_and_admin(conn)                 # roles/permissions/admin → tenant schema
        conn.commit()

        with raw.cursor() as cur:
            cur.execute(
                "INSERT INTO public.tenants (slug, schema_name, name, status, plan, created_at) "
                "VALUES (%s, %s, %s, 'active', %s, %s) ON CONFLICT (slug) DO NOTHING",
                (slug, schema, name or slug, plan, _now()))
            cur.execute("SELECT * FROM public.tenants WHERE slug=%s", (slug,))
            row = cur.fetchone()
        raw.commit()
    finally:
        raw.close()

    _CACHE.pop(slug, None)               # refresh any cached lookup
    _SCHEMA_STATUS.pop(schema, None)
    return dict(row)


def list_tenants() -> list:
    raw = _connect()
    try:
        ensure_tenants_catalog(raw)
        with raw.cursor() as cur:
            cur.execute("SELECT * FROM public.tenants ORDER BY id")
            return [dict(r) for r in cur.fetchall()]
    finally:
        raw.close()


def set_tenant_status(slug: str, status: str) -> None:
    if status not in ("active", "suspended"):
        raise ValueError("status must be 'active' or 'suspended'")
    raw = _connect()
    try:
        with raw.cursor() as cur:
            cur.execute("UPDATE public.tenants SET status=%s WHERE slug=%s", (status, slug))
        raw.commit()
    finally:
        raw.close()
    _CACHE.pop(slug, None)
    _SCHEMA_STATUS.clear()


# ── resolution (cached) ──────────────────────────────────────────────────────
# Small in-process caches. Cleared on provision / status change. A production
# deployment would back these with Redis (Phase 4); for now a lookup miss does a
# short-lived connection.
_CACHE = {}            # slug -> (schema, status)
_SCHEMA_STATUS = {}    # schema -> status


def _lookup_by_slug(slug: str):
    if slug in _CACHE:
        return _CACHE[slug]
    try:
        raw = _connect()
    except Exception:
        return None
    try:
        with raw.cursor() as cur:
            cur.execute("SELECT schema_name, status FROM public.tenants WHERE slug=%s", (slug,))
            row = cur.fetchone()
    except Exception:
        return None
    finally:
        raw.close()
    if not row:
        return None
    res = (row["schema_name"], row["status"])
    _CACHE[slug] = res
    _SCHEMA_STATUS[row["schema_name"]] = row["status"]
    return res


def _schema_is_active(schema: str) -> bool:
    if schema in _SCHEMA_STATUS:
        return _SCHEMA_STATUS[schema] == "active"
    try:
        raw = _connect()
    except Exception:
        return False
    try:
        with raw.cursor() as cur:
            cur.execute("SELECT status FROM public.tenants WHERE schema_name=%s", (schema,))
            row = cur.fetchone()
    except Exception:
        return False
    finally:
        raw.close()
    if not row:
        return False
    _SCHEMA_STATUS[schema] = row["status"]
    return row["status"] == "active"


def _schema_from_cookie(cookie_header: str):
    if not cookie_header:
        return None
    jar = SimpleCookie()
    try:
        jar.load(cookie_header)
    except Exception:
        return None
    if COOKIE_NAME not in jar:
        return None
    try:
        # Signature-verified, but ignore expiry here — expiry is enforced later by
        # require_auth. We only need the (authentic) schema claim to route the DB.
        payload = jwt.decode(jar[COOKIE_NAME].value, SECRET_KEY,
                             algorithms=[ALGORITHM], options={"verify_exp": False})
    except Exception:
        return None
    schema = payload.get("schema")
    return schema if valid_schema_name(schema) else None


def _subdomain(host: str):
    parts = host.split(".")
    if len(parts) >= 3 and parts[0] not in ("www", "app", "api"):
        return parts[0]
    return None


def resolve_schema_from_scope(scope) -> "str | None":
    headers = {k.decode("latin1").lower(): v.decode("latin1")
               for k, v in scope.get("headers", [])}

    # 1) Authenticated request → the signed JWT's schema claim is authoritative.
    schema = _schema_from_cookie(headers.get("cookie", ""))
    if schema and _schema_is_active(schema):
        return schema

    # 2) Explicit X-Tenant header (login form / API clients).
    slug = headers.get("x-tenant", "").strip().lower()
    if valid_slug(slug):
        found = _lookup_by_slug(slug)
        if found and found[1] == "active":
            return found[0]

    # 3) Host subdomain (acme.erp.app → 'acme').
    sub = _subdomain(headers.get("host", "").split(":")[0])
    if sub and valid_slug(sub):
        found = _lookup_by_slug(sub)
        if found and found[1] == "active":
            return found[0]

    return None  # unresolved → get_db falls back to `public` (no business tables)


class TenantMiddleware:
    """Pure-ASGI middleware: resolve the request's tenant schema and stash it in
    the ContextVar so get_db can pin the connection's search_path. Inert unless
    TENANCY=schema."""

    def __init__(self, app):
        self.app = app

    async def __call__(self, scope, receive, send):
        if scope.get("type") != "http" or not IS_SCHEMA_TENANCY:
            await self.app(scope, receive, send)
            return
        schema = resolve_schema_from_scope(scope)
        token = set_current_schema(schema)
        try:
            await self.app(scope, receive, send)
        finally:
            reset_current_schema(token)
