"""
Generate ``pg_baseline.sql`` — the squashed PostgreSQL schema (ADR-5).

PostgreSQL cannot replay the 123 SQLite migrations (PRAGMA, executescript, the
CREATE-new/INSERT-SELECT/DROP/RENAME rebuild pattern). Instead we ship a single
*baseline* DDL representing the FINAL shape of the schema after every migration,
and record those migrations as already-applied so the runner skips them.

This script builds a throwaway, fully-migrated SQLite database with the app's own
``database.init_db()``, introspects it via PRAGMAs (robust — no SQL-text parsing),
and emits an equivalent Postgres schema:

  * INTEGER single-column PK            → ``INTEGER GENERATED BY DEFAULT AS IDENTITY``
  * REAL → DOUBLE PRECISION,  BLOB → BYTEA,  TEXT → TEXT
  * ``DEFAULT (datetime('now'))``       → ``DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')``
  * FOREIGN KEYs are added with ALTER TABLE *after* all tables exist, so circular
    references (projects ↔ quotations) and forward references just work.
  * explicit indexes (incl. the partial unique idempotency index) are copied.
  * every applied migration name EXCEPT ``081_role_dep_view`` is pre-recorded in
    schema_migrations (081 is applied by init_db's seeding, which must still run
    on a fresh Postgres install to grant the cross-module dependency views).

Run:  python backend/migrations/generate_pg_baseline.py
Out:  backend/migrations/pg_baseline.sql

Re-run whenever the SQLite schema changes (a new migration is added) so the
Postgres baseline stays in lock-step. See docs/SAAS_ARCHITECTURE.md §6.
"""
import os
import sys
import sqlite3
import tempfile

_HERE = os.path.dirname(os.path.abspath(__file__))
_BACKEND = os.path.dirname(_HERE)
sys.path.insert(0, _BACKEND)

OUT_PATH = os.path.join(_HERE, "pg_baseline.sql")

# Migration applied by init_db()'s seeding (not _run_migrations); it must NOT be
# pre-recorded, so the dependency-view backfill runs on a fresh Postgres install.
_SEED_MIGRATION = "081_role_dep_view"

_TYPE_MAP = {
    "INTEGER": "INTEGER",
    "INT":     "INTEGER",
    "REAL":    "DOUBLE PRECISION",
    "FLOAT":   "DOUBLE PRECISION",
    "DOUBLE":  "DOUBLE PRECISION",
    "TEXT":    "TEXT",
    "BLOB":    "BYTEA",
    "NUMERIC": "NUMERIC",
    "BOOLEAN": "INTEGER",   # the app stores booleans as 0/1 INTEGERs
    "":        "TEXT",
}


def _pg_type(sqlite_type: str) -> str:
    return _TYPE_MAP.get((sqlite_type or "").strip().upper(), sqlite_type or "TEXT")


def _pg_default(dflt) -> str:
    """Translate a SQLite column default to its Postgres spelling."""
    if dflt is None:
        return ""
    from dialect import _translate_datetime
    return " DEFAULT " + _translate_datetime(str(dflt))


def _sql_literal(v) -> str:
    """Render a Python value as a Postgres SQL literal for the seed-data dump."""
    if v is None:
        return "NULL"
    if isinstance(v, bool):
        return "1" if v else "0"
    if isinstance(v, (int, float)):
        return repr(v)
    if isinstance(v, (bytes, bytearray, memoryview)):
        return "'\\x" + bytes(v).hex() + "'::bytea"
    return "'" + str(v).replace("'", "''") + "'"


def _build_sqlite_reference_db() -> str:
    tmp = tempfile.mktemp(suffix=".db")
    os.environ["DB_PATH"] = tmp
    os.environ["DB_BACKEND"] = "sqlite"
    import database
    database.init_db()
    return tmp


def main():
    db_path = _build_sqlite_reference_db()
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row

    tables = [r["name"] for r in conn.execute(
        "SELECT name FROM sqlite_master WHERE type='table' "
        "AND name NOT LIKE 'sqlite_%' ORDER BY name")]
    master_sql = {r["name"]: (r["sql"] or "") for r in conn.execute(
        "SELECT name, sql FROM sqlite_master WHERE type='table'")}

    out = []
    out.append("-- ════════════════════════════════════════════════════════════════════════")
    out.append("-- pg_baseline.sql — GENERATED by migrations/generate_pg_baseline.py")
    out.append("-- Squashed PostgreSQL schema = the final shape of all SQLite migrations.")
    out.append("-- DO NOT EDIT BY HAND. Regenerate when the SQLite schema changes.")
    out.append("-- ════════════════════════════════════════════════════════════════════════")
    out.append("")

    fk_statements = []

    for t in tables:
        cols = conn.execute(f"PRAGMA table_info('{t}')").fetchall()
        pk_cols = [c["name"] for c in sorted(
            (c for c in cols if c["pk"]), key=lambda c: c["pk"])]
        autoinc = "AUTOINCREMENT" in master_sql.get(t, "").upper()
        single_int_pk = (len(pk_cols) == 1 and
                         _pg_type(next(c["type"] for c in cols if c["name"] == pk_cols[0]))
                         == "INTEGER")

        lines = []
        for c in cols:
            name = c["name"]
            ptype = _pg_type(c["type"])
            if single_int_pk and name == pk_cols[0]:
                # Identity column replaces INTEGER PRIMARY KEY AUTOINCREMENT.
                lines.append(f"    {name} INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
                continue
            seg = f"    {name} {ptype}"
            if c["notnull"]:
                seg += " NOT NULL"
            seg += _pg_default(c["dflt_value"])
            lines.append(seg)

        # Any primary key that isn't the single INTEGER identity column handled
        # inline above: composite PKs (year, month) AND single non-integer PKs
        # such as settings.key (TEXT PRIMARY KEY).
        if pk_cols and not single_int_pk:
            lines.append(f"    PRIMARY KEY ({', '.join(pk_cols)})")

        # UNIQUE constraints (origin 'u' = declared UNIQUE; skip 'pk' and 'c').
        for idx in conn.execute(f"PRAGMA index_list('{t}')").fetchall():
            if idx["origin"] != "u":
                continue
            ucols = [r["name"] for r in conn.execute(
                f"PRAGMA index_info('{idx['name']}')").fetchall()]
            lines.append(f"    UNIQUE ({', '.join(ucols)})")

        out.append(f"CREATE TABLE IF NOT EXISTS {t} (")
        out.append(",\n".join(lines))
        out.append(");")
        out.append("")

        # Foreign keys — emitted later via ALTER TABLE so referenced tables exist.
        fks = conn.execute(f"PRAGMA foreign_key_list('{t}')").fetchall()
        by_id = {}
        for fk in fks:
            by_id.setdefault(fk["id"], []).append(fk)
        for _id, parts in sorted(by_id.items()):
            parts = sorted(parts, key=lambda p: p["seq"])
            from_cols = ", ".join(p["from"] for p in parts)
            to_cols = ", ".join(p["to"] for p in parts)
            target = parts[0]["table"]
            on_del = (parts[0]["on_delete"] or "").upper()
            clause = (f"ALTER TABLE {t} ADD FOREIGN KEY ({from_cols}) "
                      f"REFERENCES {target} ({to_cols})")
            if on_del and on_del != "NO ACTION":
                clause += f" ON DELETE {on_del}"
            fk_statements.append(clause + ";")

    # ── Seed / reference data inserted by migrations (chart of accounts, tax
    # rates, cash drawers, default settings, …). The baseline captures schema;
    # this captures the rows a fresh, fully-migrated SQLite DB already holds —
    # EXCEPT rows that _seed_roles_and_admin() recreates at runtime on Postgres.
    # Emitted BEFORE the foreign keys so ADD CONSTRAINT validates consistent data.
    _RUNTIME_SEEDED = {"roles", "role_permissions", "users", "schema_migrations"}
    data_blocks, setvals, seeded_tables = [], [], []
    for t in tables:
        if t in _RUNTIME_SEEDED:
            continue
        rows = conn.execute(f"SELECT * FROM {t}").fetchall()
        if not rows:
            continue
        colnames = list(rows[0].keys())
        col_list = ", ".join(colnames)
        values = ",\n".join(
            "    (" + ", ".join(_sql_literal(r[c]) for c in colnames) + ")"
            for r in rows)
        data_blocks.append(
            f"INSERT INTO {t} ({col_list}) VALUES\n{values}\nON CONFLICT DO NOTHING;")
        seeded_tables.append((t, len(rows)))
        if "id" in colnames:
            setvals.append(
                f"SELECT setval(pg_get_serial_sequence('{t}', 'id'), "
                f"(SELECT COALESCE(MAX(id), 1) FROM {t}));")
    if data_blocks:
        out.append("-- ── Seed / reference data (migration-inserted rows) ──────────────────────")
        out.extend(data_blocks)
        out.append("")
        out.append("-- Advance identity sequences past the seeded ids.")
        out.extend(setvals)
        out.append("")

    if fk_statements:
        out.append("-- ── Foreign keys (added after all tables exist) ──────────────────────────")
        out.extend(fk_statements)
        out.append("")

    # Explicit indexes (CREATE [UNIQUE] INDEX …) — these are PG-compatible as-is,
    # including the partial unique idempotency index.
    idx_rows = conn.execute(
        "SELECT name, sql FROM sqlite_master WHERE type='index' AND sql IS NOT NULL "
        "ORDER BY name").fetchall()
    if idx_rows:
        out.append("-- ── Indexes ──────────────────────────────────────────────────────────────")
        for r in idx_rows:
            out.append(r["sql"].strip().rstrip(";") + ";")
        out.append("")

    # Pre-record applied migrations (all except the seeding-applied 081).
    names = [r["name"] for r in conn.execute(
        "SELECT name FROM schema_migrations ORDER BY id").fetchall()]
    names = [n for n in names if n != _SEED_MIGRATION]
    out.append("-- ── Migration ledger (these are baked into the baseline above) ────────────")
    out.append("INSERT INTO schema_migrations (name, applied_at) VALUES")
    vals = ",\n".join(
        f"    ('{n}', to_char(now(), 'YYYY-MM-DD HH24:MI:SS'))" for n in names)
    out.append(vals)
    out.append("ON CONFLICT (name) DO NOTHING;")
    out.append("")

    conn.close()
    try:
        os.remove(db_path)
    except OSError:
        pass

    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(out))

    print(f"Wrote {OUT_PATH}")
    print(f"  tables : {len(tables)}")
    print(f"  fkeys  : {len(fk_statements)}")
    print(f"  indexes: {len(idx_rows)}")
    print(f"  ledger : {len(names)} migrations pre-recorded (excluded {_SEED_MIGRATION})")
    print(f"  seed   : {len(seeded_tables)} tables with reference data "
          f"({', '.join(f'{t}×{n}' for t, n in seeded_tables)})")


if __name__ == "__main__":
    main()
