-- ════════════════════════════════════════════════════════════════════════
-- pg_baseline.sql — GENERATED by migrations/generate_pg_baseline.py
-- Squashed PostgreSQL schema = the final shape of all SQLite migrations.
-- DO NOT EDIT BY HAND. Regenerate when the SQLite schema changes.
-- ════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS accounting_periods (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    year INTEGER NOT NULL,
    month INTEGER NOT NULL,
    locked_at TEXT,
    locked_by TEXT,
    UNIQUE (year, month)
);

CREATE TABLE IF NOT EXISTS announcement_comments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    announcement_id INTEGER NOT NULL,
    author_id INTEGER NOT NULL,
    author_name TEXT,
    body TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS'),
    deleted_at TEXT
);

CREATE TABLE IF NOT EXISTS announcement_recipients (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    announcement_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    read_at TEXT,
    acknowledged_at TEXT,
    UNIQUE (announcement_id, user_id)
);

CREATE TABLE IF NOT EXISTS announcements (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    body TEXT NOT NULL,
    priority TEXT NOT NULL DEFAULT 'medium',
    audience_type TEXT NOT NULL,
    audience_payload TEXT,
    requires_ack INTEGER NOT NULL DEFAULT 0,
    pinned INTEGER NOT NULL DEFAULT 0,
    author_id INTEGER NOT NULL,
    author_name TEXT,
    published_at TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS'),
    expires_at TEXT,
    archived_at TEXT
);

CREATE TABLE IF NOT EXISTS approval_comments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id INTEGER NOT NULL,
    user_id INTEGER,
    comment TEXT NOT NULL,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS approval_policies (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    module TEXT NOT NULL,
    trigger_action TEXT NOT NULL DEFAULT 'create',
    condition_logic TEXT NOT NULL DEFAULT 'AND',
    conditions TEXT NOT NULL DEFAULT '[]',
    approval_type TEXT NOT NULL DEFAULT 'single',
    approver_roles TEXT NOT NULL DEFAULT '[]',
    steps TEXT NOT NULL DEFAULT '[]',
    priority INTEGER NOT NULL DEFAULT 0,
    is_active INTEGER NOT NULL DEFAULT 1,
    created_by INTEGER,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS approval_requests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_id INTEGER,
    policy_name TEXT NOT NULL,
    module TEXT NOT NULL,
    entity_id INTEGER NOT NULL,
    entity_label TEXT,
    trigger_action TEXT NOT NULL,
    entity_snapshot TEXT,
    status TEXT NOT NULL DEFAULT 'pending',
    approval_type TEXT NOT NULL DEFAULT 'single',
    current_step INTEGER NOT NULL DEFAULT 1,
    total_steps INTEGER NOT NULL DEFAULT 1,
    requested_by INTEGER,
    requested_at TEXT NOT NULL,
    resolved_at TEXT,
    resolved_by INTEGER,
    resolution_comment TEXT
);

CREATE TABLE IF NOT EXISTS approval_steps (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id INTEGER NOT NULL,
    step_number INTEGER NOT NULL,
    approver_role TEXT NOT NULL,
    approver_user_id INTEGER,
    status TEXT NOT NULL DEFAULT 'pending',
    acted_at TEXT,
    comment TEXT
);

CREATE TABLE IF NOT EXISTS asset_depreciation (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id INTEGER NOT NULL,
    period TEXT NOT NULL,
    amount DOUBLE PRECISION NOT NULL DEFAULT 0,
    accumulated_after DOUBLE PRECISION NOT NULL DEFAULT 0,
    book_value_after DOUBLE PRECISION NOT NULL DEFAULT 0,
    expense_id INTEGER,
    posted_at TEXT NOT NULL,
    posted_by INTEGER,
    UNIQUE (asset_id, period)
);

CREATE TABLE IF NOT EXISTS attachments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type TEXT NOT NULL,
    entity_id INTEGER NOT NULL,
    filename TEXT NOT NULL,
    content_type TEXT NOT NULL,
    size_bytes INTEGER NOT NULL,
    data BYTEA NOT NULL,
    uploaded_by INTEGER,
    uploaded_by_name TEXT,
    created_at TEXT NOT NULL,
    storage_backend TEXT NOT NULL DEFAULT 'db',
    storage_key TEXT
);

CREATE TABLE IF NOT EXISTS audit_log (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER,
    username TEXT,
    action TEXT NOT NULL,
    module TEXT NOT NULL,
    record_id INTEGER,
    record_ref TEXT,
    detail TEXT,
    created_at TEXT NOT NULL,
    prev_hash TEXT,
    row_hash TEXT
);

CREATE TABLE IF NOT EXISTS bom_components (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bom_id INTEGER NOT NULL,
    component_inventory_id INTEGER NOT NULL,
    quantity DOUBLE PRECISION NOT NULL DEFAULT 1,
    scrap_pct DOUBLE PRECISION NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS bom_operations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bom_id INTEGER NOT NULL,
    sequence INTEGER NOT NULL DEFAULT 1,
    name TEXT NOT NULL,
    work_center_id INTEGER,
    setup_minutes DOUBLE PRECISION NOT NULL DEFAULT 0,
    run_minutes_per_unit DOUBLE PRECISION NOT NULL DEFAULT 0,
    notes TEXT
);

CREATE TABLE IF NOT EXISTS bom_resources (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bom_id INTEGER NOT NULL,
    resource_id INTEGER,
    name TEXT NOT NULL,
    hourly_rate DOUBLE PRECISION NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS boms (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    output_inventory_id INTEGER NOT NULL,
    output_quantity DOUBLE PRECISION NOT NULL DEFAULT 1,
    labor_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
    notes TEXT,
    is_active INTEGER NOT NULL DEFAULT 1,
    archived_at TEXT,
    created_at TEXT NOT NULL,
    version INTEGER NOT NULL DEFAULT 1,
    bom_group_id INTEGER,
    overhead_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
    revision_note TEXT,
    qc_required INTEGER NOT NULL DEFAULT 0,
    standard_hours DOUBLE PRECISION NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS cash_drawers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    is_active INTEGER NOT NULL DEFAULT 1,
    auto_capture INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS cash_movements (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reconciliation_id INTEGER NOT NULL,
    direction TEXT NOT NULL,
    amount DOUBLE PRECISION NOT NULL,
    category TEXT,
    description TEXT,
    created_by INTEGER,
    created_by_name TEXT,
    created_at TEXT NOT NULL,
    currency TEXT NOT NULL DEFAULT 'USD'
);

CREATE TABLE IF NOT EXISTS cash_reconciliations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    drawer_id INTEGER NOT NULL,
    business_date TEXT NOT NULL,
    opening_balance DOUBLE PRECISION NOT NULL DEFAULT 0,
    counted_cash DOUBLE PRECISION,
    expected_cash DOUBLE PRECISION,
    variance DOUBLE PRECISION,
    status TEXT NOT NULL DEFAULT 'open',
    note TEXT,
    opened_by INTEGER,
    opened_by_name TEXT,
    opened_at TEXT NOT NULL,
    closed_by INTEGER,
    closed_by_name TEXT,
    closed_at TEXT,
    opening_balance_lbp DOUBLE PRECISION NOT NULL DEFAULT 0,
    counted_cash_lbp DOUBLE PRECISION,
    expected_cash_lbp DOUBLE PRECISION,
    variance_lbp DOUBLE PRECISION,
    UNIQUE (drawer_id, business_date)
);

CREATE TABLE IF NOT EXISTS chart_of_accounts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    type TEXT NOT NULL,
    subtype TEXT,
    normal_balance TEXT NOT NULL,
    parent_code TEXT,
    is_system INTEGER NOT NULL DEFAULT 0,
    is_active INTEGER NOT NULL DEFAULT 1,
    description TEXT,
    created_at TEXT NOT NULL,
    UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS clients (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    company TEXT,
    phone TEXT,
    email TEXT,
    address TEXT,
    type TEXT DEFAULT 'private',
    notes TEXT,
    created_at TEXT,
    deleted_at TEXT DEFAULT NULL,
    archived_at TEXT DEFAULT NULL,
    archive_reason TEXT DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS crm_activities (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TEXT NOT NULL,
    subject TEXT NOT NULL,
    description TEXT,
    client_id INTEGER,
    lead_id INTEGER,
    contact_id INTEGER,
    user_id INTEGER,
    due_date TEXT,
    done_at TEXT,
    outcome TEXT,
    archived_at TEXT DEFAULT NULL,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS crm_contacts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id INTEGER,
    lead_id INTEGER,
    name TEXT NOT NULL,
    title TEXT,
    email TEXT,
    phone TEXT,
    is_primary INTEGER DEFAULT 0,
    notes TEXT,
    archived_at TEXT DEFAULT NULL,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS crm_deals (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    client_id INTEGER,
    lead_id INTEGER,
    quotation_id INTEGER,
    stage TEXT DEFAULT 'Prospect',
    value DOUBLE PRECISION DEFAULT 0,
    probability INTEGER DEFAULT 0,
    expected_close TEXT,
    won_at TEXT,
    lost_at TEXT,
    lost_reason TEXT,
    assigned_to INTEGER,
    notes TEXT,
    archived_at TEXT DEFAULT NULL,
    created_at TEXT NOT NULL,
    archive_reason TEXT DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS crm_leads (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    company TEXT,
    email TEXT,
    phone TEXT,
    source TEXT DEFAULT 'Other',
    status TEXT DEFAULT 'New',
    score INTEGER DEFAULT 0,
    estimated_value DOUBLE PRECISION DEFAULT 0,
    expected_close TEXT,
    assigned_to INTEGER,
    client_id INTEGER,
    notes TEXT,
    archived_at TEXT DEFAULT NULL,
    created_at TEXT NOT NULL,
    archive_reason TEXT DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS documents (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_type TEXT NOT NULL,
    record_id INTEGER NOT NULL,
    client_id INTEGER,
    project_id INTEGER,
    title TEXT NOT NULL,
    html_content TEXT NOT NULL,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS exchange_rates (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rate DOUBLE PRECISION NOT NULL,
    set_by INTEGER,
    set_by_name TEXT,
    note TEXT,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS expenses (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id INTEGER,
    category TEXT NOT NULL,
    description TEXT,
    amount DOUBLE PRECISION DEFAULT 0,
    date TEXT,
    created_at TEXT,
    deleted_at TEXT DEFAULT NULL,
    voided_at TEXT DEFAULT NULL,
    void_reason TEXT DEFAULT NULL,
    archived_at TEXT DEFAULT NULL,
    archive_reason TEXT DEFAULT NULL,
    status TEXT NOT NULL DEFAULT 'Recorded',
    tax_rate_id INTEGER,
    tax_rate DOUBLE PRECISION NOT NULL DEFAULT 0,
    tax_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
    payment_method TEXT,
    cash_drawer_id INTEGER,
    recurring_expense_id INTEGER,
    fixed_asset_id INTEGER
);

CREATE TABLE IF NOT EXISTS fiscal_years (
    year INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status TEXT NOT NULL DEFAULT 'open',
    total_income DOUBLE PRECISION NOT NULL DEFAULT 0,
    total_expense DOUBLE PRECISION NOT NULL DEFAULT 0,
    net_income DOUBLE PRECISION NOT NULL DEFAULT 0,
    closing_entry_id INTEGER,
    closed_at TEXT,
    closed_by INTEGER,
    notes TEXT
);

CREATE TABLE IF NOT EXISTS fixed_assets (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_code TEXT NOT NULL,
    name TEXT NOT NULL,
    category TEXT,
    description TEXT,
    acquisition_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
    acquisition_date TEXT NOT NULL,
    in_service_date TEXT,
    depreciation_method TEXT NOT NULL DEFAULT 'straight_line',
    useful_life_months INTEGER NOT NULL DEFAULT 0,
    salvage_value DOUBLE PRECISION NOT NULL DEFAULT 0,
    accumulated_depreciation DOUBLE PRECISION NOT NULL DEFAULT 0,
    last_depreciated_period TEXT,
    status TEXT NOT NULL DEFAULT 'Active',
    supplier_id INTEGER,
    disposal_date TEXT,
    disposal_proceeds DOUBLE PRECISION,
    disposal_reason TEXT,
    archived_at TEXT,
    created_by INTEGER,
    created_at TEXT NOT NULL,
    UNIQUE (asset_code)
);

CREATE TABLE IF NOT EXISTS hr_activities (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id INTEGER NOT NULL,
    activity_type TEXT NOT NULL DEFAULT 'Meeting',
    subject TEXT NOT NULL,
    description TEXT,
    scheduled_at TEXT NOT NULL,
    duration_min INTEGER NOT NULL DEFAULT 30,
    location TEXT,
    status TEXT NOT NULL DEFAULT 'Planned',
    applicant_id INTEGER,
    employee_id INTEGER,
    reminder_minutes_before INTEGER NOT NULL DEFAULT 15,
    reminder_notif_id INTEGER,
    completed_at TEXT,
    completed_notes TEXT,
    archived_at TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT
);

CREATE TABLE IF NOT EXISTS hr_contracts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id INTEGER NOT NULL,
    contract_number TEXT,
    contract_type TEXT NOT NULL DEFAULT 'Permanent',
    status TEXT NOT NULL DEFAULT 'Draft',
    start_date TEXT NOT NULL,
    end_date TEXT,
    probation_end_date TEXT,
    job_title TEXT,
    work_schedule TEXT,
    weekly_hours DOUBLE PRECISION,
    salary DOUBLE PRECISION NOT NULL DEFAULT 0,
    salary_currency TEXT DEFAULT 'USD',
    benefits TEXT,
    terms TEXT,
    signed_at TEXT,
    terminated_at TEXT,
    terminated_reason TEXT,
    created_by INTEGER,
    archived_at TEXT,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS hr_departments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    archived_at TEXT,
    archive_reason TEXT,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS hr_employee_files (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id INTEGER NOT NULL,
    kind TEXT NOT NULL DEFAULT 'other',
    filename TEXT NOT NULL,
    content_type TEXT NOT NULL DEFAULT 'application/pdf',
    size_bytes INTEGER NOT NULL DEFAULT 0,
    data BYTEA NOT NULL,
    uploaded_by INTEGER,
    created_at TEXT NOT NULL,
    storage_backend TEXT NOT NULL DEFAULT 'db',
    storage_key TEXT
);

CREATE TABLE IF NOT EXISTS hr_employees (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_code TEXT,
    full_name TEXT NOT NULL,
    job_title TEXT,
    department_id INTEGER,
    employment_type TEXT NOT NULL DEFAULT 'Full-time',
    status TEXT NOT NULL DEFAULT 'Active',
    hire_date TEXT,
    end_date TEXT,
    email TEXT,
    phone TEXT,
    salary DOUBLE PRECISION DEFAULT 0,
    manager_id INTEGER,
    user_id INTEGER,
    address TEXT,
    notes TEXT,
    archived_at TEXT,
    archive_reason TEXT,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS hr_employment_changes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id INTEGER NOT NULL,
    effective_date TEXT NOT NULL,
    change_type TEXT NOT NULL DEFAULT 'adjustment',
    old_salary DOUBLE PRECISION,
    new_salary DOUBLE PRECISION,
    old_title TEXT,
    new_title TEXT,
    old_department_id INTEGER,
    new_department_id INTEGER,
    old_manager_id INTEGER,
    new_manager_id INTEGER,
    reason TEXT,
    created_by INTEGER,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS hr_leave_requests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id INTEGER NOT NULL,
    leave_type TEXT NOT NULL DEFAULT 'Annual',
    start_date TEXT NOT NULL,
    end_date TEXT NOT NULL,
    days DOUBLE PRECISION NOT NULL DEFAULT 0,
    reason TEXT,
    status TEXT NOT NULL DEFAULT 'Pending',
    reviewed_by INTEGER,
    reviewed_at TEXT,
    review_note TEXT,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS hr_attendance (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id INTEGER NOT NULL,
    date TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'Present',
    hours DOUBLE PRECISION,
    note TEXT,
    created_at TEXT,
    updated_at TEXT,
    UNIQUE(employee_id, date)
);
CREATE INDEX IF NOT EXISTS idx_hr_attendance_date ON hr_attendance(date);
CREATE INDEX IF NOT EXISTS idx_hr_attendance_emp ON hr_attendance(employee_id);

CREATE TABLE IF NOT EXISTS hr_payroll_lines (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payroll_run_id INTEGER NOT NULL,
    employee_id INTEGER NOT NULL,
    base_salary DOUBLE PRECISION NOT NULL DEFAULT 0,
    bonuses DOUBLE PRECISION NOT NULL DEFAULT 0,
    deductions DOUBLE PRECISION NOT NULL DEFAULT 0,
    net_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
    notes TEXT,
    created_at TEXT NOT NULL,
    tax_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
    nssf_employee DOUBLE PRECISION NOT NULL DEFAULT 0,
    nssf_employer DOUBLE PRECISION NOT NULL DEFAULT 0,
    overtime_hours DOUBLE PRECISION NOT NULL DEFAULT 0,
    overtime_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
    gross_total DOUBLE PRECISION NOT NULL DEFAULT 0,
    salary_currency TEXT NOT NULL DEFAULT 'USD',
    UNIQUE (payroll_run_id, employee_id)
);

CREATE TABLE IF NOT EXISTS hr_payroll_runs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    period_start TEXT NOT NULL,
    period_end TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'Draft',
    total_gross DOUBLE PRECISION NOT NULL DEFAULT 0,
    total_bonuses DOUBLE PRECISION NOT NULL DEFAULT 0,
    total_deductions DOUBLE PRECISION NOT NULL DEFAULT 0,
    total_net DOUBLE PRECISION NOT NULL DEFAULT 0,
    posted_expense_id INTEGER,
    notes TEXT,
    approved_at TEXT,
    approved_by INTEGER,
    paid_at TEXT,
    paid_by INTEGER,
    archived_at TEXT,
    created_by INTEGER,
    created_at TEXT NOT NULL,
    total_tax DOUBLE PRECISION NOT NULL DEFAULT 0,
    total_nssf_employee DOUBLE PRECISION NOT NULL DEFAULT 0,
    total_nssf_employer DOUBLE PRECISION NOT NULL DEFAULT 0,
    total_overtime DOUBLE PRECISION NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS inventory (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT,
    quantity DOUBLE PRECISION DEFAULT 0,
    min_stock DOUBLE PRECISION DEFAULT 0,
    unit_cost DOUBLE PRECISION DEFAULT 0,
    supplier TEXT,
    unit TEXT DEFAULT 'pcs',
    created_at TEXT,
    deleted_at TEXT DEFAULT NULL,
    archived_at TEXT DEFAULT NULL,
    archive_reason TEXT DEFAULT NULL,
    barcode TEXT,
    sale_price DOUBLE PRECISION NOT NULL DEFAULT 0,
    product_type TEXT,
    reserved_quantity DOUBLE PRECISION NOT NULL DEFAULT 0,
    quarantine_quantity DOUBLE PRECISION NOT NULL DEFAULT 0,
    lot_tracked INTEGER NOT NULL DEFAULT 0,
    shelf_life_days INTEGER,
    price_currency TEXT DEFAULT 'USD',
    product_id INTEGER,
    variant_label TEXT
);

-- Product variants + attributes (migration 134). inventory is the SKU level;
-- a product groups variants. product_id NULL on an inventory row = simple item.
CREATE TABLE IF NOT EXISTS products (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT,
    brand TEXT,
    description TEXT,
    product_kind TEXT NOT NULL DEFAULT 'variant',
    barcode TEXT,
    created_at TEXT,
    archived_at TEXT
);
CREATE INDEX IF NOT EXISTS idx_products_category ON products(category);
CREATE INDEX IF NOT EXISTS idx_inventory_product ON inventory(product_id);

CREATE TABLE IF NOT EXISTS attribute_defs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope_type TEXT NOT NULL DEFAULT 'global',
    scope_value TEXT,
    name TEXT NOT NULL,
    input_type TEXT NOT NULL DEFAULT 'enum',
    options TEXT,
    is_variant_axis INTEGER NOT NULL DEFAULT 1,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TEXT,
    UNIQUE(scope_type, scope_value, name)
);

CREATE TABLE IF NOT EXISTS item_attributes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_id INTEGER NOT NULL REFERENCES inventory(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    value TEXT,
    UNIQUE(inventory_id, name)
);
CREATE INDEX IF NOT EXISTS idx_item_attributes_inv ON item_attributes(inventory_id);
CREATE INDEX IF NOT EXISTS idx_item_attributes_nv ON item_attributes(name, value);

CREATE TABLE IF NOT EXISTS product_attributes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    value TEXT,
    UNIQUE(product_id, name)
);
CREATE INDEX IF NOT EXISTS idx_product_attributes_pid ON product_attributes(product_id);

CREATE TABLE IF NOT EXISTS inventory_cost_layers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_id INTEGER NOT NULL,
    qty_remaining DOUBLE PRECISION NOT NULL,
    unit_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
    source_type TEXT,
    source_ref TEXT,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS inventory_lots (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_id INTEGER NOT NULL,
    lot_number TEXT,
    quantity_remaining DOUBLE PRECISION NOT NULL DEFAULT 0,
    original_quantity DOUBLE PRECISION NOT NULL DEFAULT 0,
    unit_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
    manufacture_date TEXT,
    expiry_date TEXT,
    source_type TEXT,
    source_ref TEXT,
    status TEXT NOT NULL DEFAULT 'active',
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS inventory_stock (
    inventory_id INTEGER NOT NULL,
    warehouse_id INTEGER NOT NULL,
    quantity DOUBLE PRECISION NOT NULL DEFAULT 0,
    reserved_quantity DOUBLE PRECISION NOT NULL DEFAULT 0,
    quarantine_quantity DOUBLE PRECISION NOT NULL DEFAULT 0,
    PRIMARY KEY (inventory_id, warehouse_id)
);

CREATE TABLE IF NOT EXISTS invoice_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id INTEGER NOT NULL,
    name TEXT NOT NULL,
    quantity DOUBLE PRECISION NOT NULL DEFAULT 1,
    unit_price DOUBLE PRECISION NOT NULL DEFAULT 0,
    tax_rate_id INTEGER,
    tax_rate DOUBLE PRECISION NOT NULL DEFAULT 0,
    tax_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
    discount DOUBLE PRECISION NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS invoice_payments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id INTEGER NOT NULL,
    amount DOUBLE PRECISION NOT NULL,
    method TEXT DEFAULT 'Cash',
    note TEXT,
    idempotency_key TEXT DEFAULT NULL,
    paid_at TEXT,
    paid_currency TEXT NOT NULL DEFAULT 'USD',
    paid_amount DOUBLE PRECISION,
    exchange_rate DOUBLE PRECISION,
    cash_drawer_id INTEGER
);

CREATE TABLE IF NOT EXISTS invoices (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_number TEXT NOT NULL,
    quotation_id INTEGER,
    project_id INTEGER,
    client_id INTEGER,
    amount DOUBLE PRECISION DEFAULT 0,
    due_date TEXT,
    notes TEXT,
    version INTEGER NOT NULL DEFAULT 1,
    voided_at TEXT DEFAULT NULL,
    void_reason TEXT DEFAULT NULL,
    created_at TEXT,
    deleted_at TEXT DEFAULT NULL,
    archived_at TEXT DEFAULT NULL,
    archive_reason TEXT DEFAULT NULL,
    subtotal DOUBLE PRECISION NOT NULL DEFAULT 0,
    tax_total DOUBLE PRECISION NOT NULL DEFAULT 0,
    approval_status TEXT DEFAULT NULL,
    UNIQUE (invoice_number)
);

CREATE TABLE IF NOT EXISTS journal_entries (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_number TEXT,
    entry_date TEXT NOT NULL,
    memo TEXT,
    source_type TEXT,
    source_id INTEGER,
    status TEXT NOT NULL DEFAULT 'posted',
    reverses_id INTEGER,
    reversed_by INTEGER,
    total_debit DOUBLE PRECISION NOT NULL DEFAULT 0,
    total_credit DOUBLE PRECISION NOT NULL DEFAULT 0,
    created_by INTEGER,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS journal_entry_lines (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    journal_entry_id INTEGER NOT NULL,
    account_id INTEGER NOT NULL,
    debit DOUBLE PRECISION NOT NULL DEFAULT 0,
    credit DOUBLE PRECISION NOT NULL DEFAULT 0,
    memo TEXT,
    line_no INTEGER
);

CREATE TABLE IF NOT EXISTS login_attempts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ip TEXT NOT NULL,
    attempted_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS lot_consumption (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lot_id INTEGER NOT NULL,
    inventory_id INTEGER NOT NULL,
    quantity DOUBLE PRECISION NOT NULL DEFAULT 0,
    unit_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
    source_type TEXT,
    source_ref TEXT,
    production_order_id INTEGER,
    output_lot_id INTEGER,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS manufacturing_resources (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    cost_type TEXT NOT NULL DEFAULT 'per_hour',
    hourly_rate DOUBLE PRECISION NOT NULL DEFAULT 0,
    is_active INTEGER NOT NULL DEFAULT 1,
    notes TEXT,
    archived_at TEXT,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS notifications (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER,
    type TEXT NOT NULL,
    title TEXT NOT NULL,
    body TEXT,
    link TEXT,
    entity_type TEXT,
    entity_id INTEGER,
    is_read INTEGER NOT NULL DEFAULT 0,
    read_at TEXT,
    created_at TEXT NOT NULL,
    deliver_at TEXT DEFAULT NULL,
    msg_key TEXT,
    params TEXT
);

CREATE TABLE IF NOT EXISTS period_snapshots (
    year INTEGER NOT NULL,
    month INTEGER NOT NULL,
    income DOUBLE PRECISION NOT NULL DEFAULT 0,
    expenses DOUBLE PRECISION NOT NULL DEFAULT 0,
    profit DOUBLE PRECISION NOT NULL DEFAULT 0,
    payment_count INTEGER NOT NULL DEFAULT 0,
    expense_count INTEGER NOT NULL DEFAULT 0,
    locked_at TEXT NOT NULL,
    locked_by TEXT,
    PRIMARY KEY (year, month)
);

CREATE TABLE IF NOT EXISTS planning_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    start_date TEXT NOT NULL,
    end_date TEXT,
    start_time TEXT,
    end_time TEXT,
    all_day INTEGER NOT NULL DEFAULT 1,
    color TEXT,
    owner_id INTEGER,
    owner_name TEXT,
    created_at TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS'),
    updated_at TEXT,
    archived_at TEXT,
    attendees TEXT DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS planning_milestones (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id INTEGER NOT NULL,
    name TEXT NOT NULL,
    due_date TEXT,
    reached_at TEXT,
    created_at TEXT NOT NULL,
    archived_at TEXT
);

CREATE TABLE IF NOT EXISTS planning_projects (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    client_id INTEGER,
    color TEXT DEFAULT '#4f8ef7',
    start_date TEXT,
    end_date TEXT,
    status TEXT DEFAULT 'Active',
    created_by INTEGER,
    archived_at TEXT DEFAULT NULL,
    created_at TEXT NOT NULL,
    archive_reason TEXT DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS planning_tasks (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id INTEGER NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    assigned_to INTEGER,
    status TEXT DEFAULT 'To Do',
    priority TEXT DEFAULT 'Medium',
    start_date TEXT,
    end_date TEXT,
    progress INTEGER DEFAULT 0,
    milestone_id INTEGER,
    depends_on INTEGER,
    color TEXT,
    sort_order INTEGER DEFAULT 0,
    archived_at TEXT DEFAULT NULL,
    created_at TEXT NOT NULL,
    archive_reason TEXT DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS pos_returns (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pos_sale_id INTEGER NOT NULL,
    session_id INTEGER NOT NULL,
    invoice_id INTEGER NOT NULL,
    cashier_id INTEGER NOT NULL,
    refund_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
    reason TEXT,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS pos_sale_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pos_sale_id INTEGER NOT NULL,
    invoice_item_id INTEGER,
    inventory_id INTEGER,
    name TEXT NOT NULL,
    quantity DOUBLE PRECISION NOT NULL DEFAULT 1,
    unit_price DOUBLE PRECISION NOT NULL DEFAULT 0,
    line_type TEXT NOT NULL DEFAULT 'product',
    discount DOUBLE PRECISION NOT NULL DEFAULT 0,
    unit_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
    promotion_id INTEGER
);

-- Promotions: automatic POS discounts (migration 135). Percentage off an item,
-- category, or the whole store, bounded by a date window and/or a quantity cap.
CREATE TABLE IF NOT EXISTS promotions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    scope_type TEXT NOT NULL DEFAULT 'all',
    scope_value TEXT,
    discount_type TEXT NOT NULL DEFAULT 'percent',
    discount_value DOUBLE PRECISION NOT NULL DEFAULT 0,
    start_date TEXT,
    end_date TEXT,
    max_quantity INTEGER,
    used_quantity INTEGER NOT NULL DEFAULT 0,
    active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT,
    archived_at TEXT
);
CREATE INDEX IF NOT EXISTS idx_promotions_active ON promotions(active, scope_type);

-- Owner-defined category registry (migration 136), per domain.
CREATE TABLE IF NOT EXISTS categories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain TEXT NOT NULL,
    name TEXT NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT,
    archived_at TEXT,
    account_code TEXT,
    UNIQUE(domain, name)
);
CREATE INDEX IF NOT EXISTS idx_categories_domain ON categories(domain, active);

CREATE TABLE IF NOT EXISTS pos_sales (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id INTEGER NOT NULL,
    invoice_id INTEGER NOT NULL,
    cashier_id INTEGER NOT NULL,
    cashier_name TEXT,
    payment_method TEXT NOT NULL DEFAULT 'Cash',
    paid_currency TEXT NOT NULL DEFAULT 'USD',
    amount_tendered DOUBLE PRECISION NOT NULL DEFAULT 0,
    change_given DOUBLE PRECISION NOT NULL DEFAULT 0,
    total_usd DOUBLE PRECISION NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'completed',
    returned_at TEXT,
    created_at TEXT NOT NULL,
    discount_total DOUBLE PRECISION NOT NULL DEFAULT 0,
    cogs_total DOUBLE PRECISION NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS pos_sessions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cashier_id INTEGER NOT NULL,
    cashier_name TEXT,
    status TEXT NOT NULL DEFAULT 'open',
    opening_float DOUBLE PRECISION NOT NULL DEFAULT 0,
    closing_count DOUBLE PRECISION,
    expected_cash DOUBLE PRECISION,
    variance DOUBLE PRECISION,
    note TEXT,
    opened_at TEXT NOT NULL,
    closed_at TEXT,
    opening_float_lbp DOUBLE PRECISION NOT NULL DEFAULT 0,
    closing_count_lbp DOUBLE PRECISION,
    expected_cash_lbp DOUBLE PRECISION,
    variance_lbp DOUBLE PRECISION,
    warehouse_id INTEGER
);

CREATE TABLE IF NOT EXISTS production_order_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    production_order_id INTEGER NOT NULL,
    component_inventory_id INTEGER,
    name TEXT NOT NULL,
    quantity_required DOUBLE PRECISION NOT NULL DEFAULT 0,
    unit_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
    line_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
    quantity_consumed DOUBLE PRECISION,
    quantity_scrapped DOUBLE PRECISION NOT NULL DEFAULT 0,
    scrap_pct DOUBLE PRECISION NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS production_order_operations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    production_order_id INTEGER NOT NULL,
    sequence INTEGER NOT NULL DEFAULT 1,
    name TEXT NOT NULL,
    work_center_id INTEGER,
    work_center_name TEXT,
    planned_minutes DOUBLE PRECISION NOT NULL DEFAULT 0,
    actual_minutes DOUBLE PRECISION,
    status TEXT NOT NULL DEFAULT 'Pending',
    labor_rate DOUBLE PRECISION NOT NULL DEFAULT 0,
    machine_rate DOUBLE PRECISION NOT NULL DEFAULT 0,
    overhead_rate DOUBLE PRECISION NOT NULL DEFAULT 0,
    power_kw DOUBLE PRECISION NOT NULL DEFAULT 0,
    electricity_tariff DOUBLE PRECISION NOT NULL DEFAULT 0,
    labor_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
    machine_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
    electricity_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
    overhead_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
    operation_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS production_order_resources (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    production_order_id INTEGER NOT NULL,
    resource_id INTEGER,
    name TEXT NOT NULL,
    hourly_rate DOUBLE PRECISION NOT NULL DEFAULT 0,
    hours DOUBLE PRECISION NOT NULL DEFAULT 0,
    cost DOUBLE PRECISION NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS production_orders (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number TEXT NOT NULL,
    bom_id INTEGER,
    output_inventory_id INTEGER NOT NULL,
    quantity DOUBLE PRECISION NOT NULL DEFAULT 1,
    status TEXT NOT NULL DEFAULT 'Draft',
    labor_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
    materials_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
    total_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
    unit_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
    notes TEXT,
    started_at TEXT,
    completed_at TEXT,
    cancelled_at TEXT,
    cancel_reason TEXT,
    archived_at TEXT,
    created_by INTEGER,
    created_at TEXT NOT NULL,
    quantity_produced DOUBLE PRECISION,
    overhead_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
    scrap_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
    confirmed_at TEXT,
    bom_version INTEGER,
    machine_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
    electricity_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
    qc_required INTEGER NOT NULL DEFAULT 0,
    rework_of_order_id INTEGER,
    priority TEXT NOT NULL DEFAULT 'Normal',
    planned_start_date TEXT,
    due_date TEXT,
    quantity_completed DOUBLE PRECISION NOT NULL DEFAULT 0,
    production_hours DOUBLE PRECISION NOT NULL DEFAULT 0,
    warehouse_id INTEGER,
    UNIQUE (order_number)
);

CREATE TABLE IF NOT EXISTS production_qc (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    production_order_id INTEGER NOT NULL,
    output_inventory_id INTEGER NOT NULL,
    quantity DOUBLE PRECISION NOT NULL DEFAULT 0,
    unit_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
    passed_qty DOUBLE PRECISION NOT NULL DEFAULT 0,
    rejected_qty DOUBLE PRECISION NOT NULL DEFAULT 0,
    rework_qty DOUBLE PRECISION NOT NULL DEFAULT 0,
    scrap_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'Pending',
    notes TEXT,
    inspector_id INTEGER,
    inspected_at TEXT,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS production_qc_defects (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    qc_id INTEGER NOT NULL,
    reason TEXT NOT NULL,
    quantity DOUBLE PRECISION NOT NULL DEFAULT 0,
    notes TEXT
);

CREATE TABLE IF NOT EXISTS projects (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    client_id INTEGER,
    location TEXT,
    status TEXT DEFAULT 'Inquiry',
    start_date TEXT,
    end_date TEXT,
    estimated_cost DOUBLE PRECISION DEFAULT 0,
    actual_cost DOUBLE PRECISION DEFAULT 0,
    expected_revenue DOUBLE PRECISION DEFAULT 0,
    source_quotation_id INTEGER,
    description TEXT,
    created_at TEXT,
    deleted_at TEXT DEFAULT NULL,
    archived_at TEXT DEFAULT NULL,
    archive_reason TEXT DEFAULT NULL,
    void_prev_status TEXT DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS purchases (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    po_number TEXT NOT NULL,
    supplier TEXT NOT NULL,
    supplier_id INTEGER,
    inventory_id INTEGER,
    product_name TEXT NOT NULL,
    category TEXT,
    quantity DOUBLE PRECISION NOT NULL,
    unit_cost DOUBLE PRECISION DEFAULT 0,
    additional_costs DOUBLE PRECISION DEFAULT 0,
    status TEXT DEFAULT 'Ordered',
    stock_updated INTEGER DEFAULT 0,
    expense_recorded INTEGER DEFAULT 0,
    notes TEXT,
    ordered_at TEXT,
    received_at TEXT,
    paid_at TEXT,
    deleted_at TEXT DEFAULT NULL,
    archived_at TEXT DEFAULT NULL,
    archive_reason TEXT DEFAULT NULL,
    tax_rate_id INTEGER,
    tax_rate DOUBLE PRECISION NOT NULL DEFAULT 0,
    tax_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
    warehouse_id INTEGER,
    cost_currency TEXT DEFAULT 'USD',
    cost_exchange_rate DOUBLE PRECISION,
    UNIQUE (po_number)
);

CREATE TABLE IF NOT EXISTS quotation_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quotation_id INTEGER NOT NULL,
    name TEXT NOT NULL,
    quantity DOUBLE PRECISION DEFAULT 1,
    unit_price DOUBLE PRECISION DEFAULT 0,
    total DOUBLE PRECISION DEFAULT 0,
    tax_rate_id INTEGER,
    tax_rate DOUBLE PRECISION NOT NULL DEFAULT 0,
    tax_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
    discount DOUBLE PRECISION NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS quotations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quote_number TEXT NOT NULL,
    project_id INTEGER,
    client_id INTEGER,
    lead_id INTEGER,
    project_name TEXT DEFAULT NULL,
    status TEXT DEFAULT 'Draft',
    notes TEXT,
    total DOUBLE PRECISION DEFAULT 0,
    created_at TEXT,
    deleted_at TEXT DEFAULT NULL,
    archived_at TEXT DEFAULT NULL,
    archive_reason TEXT DEFAULT NULL,
    tax_total DOUBLE PRECISION NOT NULL DEFAULT 0,
    void_prev_status TEXT DEFAULT NULL,
    UNIQUE (quote_number)
);

CREATE TABLE IF NOT EXISTS recruitment_applicant_files (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    applicant_id INTEGER NOT NULL,
    kind TEXT NOT NULL DEFAULT 'cv',
    filename TEXT NOT NULL,
    content_type TEXT NOT NULL DEFAULT 'application/pdf',
    size_bytes INTEGER NOT NULL DEFAULT 0,
    data BYTEA NOT NULL,
    uploaded_by INTEGER,
    created_at TEXT NOT NULL,
    storage_backend TEXT NOT NULL DEFAULT 'db',
    storage_key TEXT
);

CREATE TABLE IF NOT EXISTS recruitment_applicants (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    position_id INTEGER,
    full_name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    source TEXT DEFAULT 'Other',
    expected_salary DOUBLE PRECISION,
    offered_salary DOUBLE PRECISION,
    status TEXT NOT NULL DEFAULT 'Applied',
    rating INTEGER,
    rejected_reason TEXT,
    notes TEXT,
    assigned_to INTEGER,
    converted_employee_id INTEGER,
    applied_at TEXT NOT NULL,
    last_status_change TEXT,
    archived_at TEXT,
    created_by INTEGER,
    created_at TEXT NOT NULL,
    accepted_reason TEXT
);

CREATE TABLE IF NOT EXISTS recruitment_interviews (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    applicant_id INTEGER NOT NULL,
    interview_type TEXT NOT NULL DEFAULT 'Phone',
    scheduled_at TEXT NOT NULL,
    duration_min INTEGER DEFAULT 60,
    location TEXT,
    interviewer_id INTEGER,
    interviewer_name TEXT,
    status TEXT NOT NULL DEFAULT 'Scheduled',
    score INTEGER,
    decision TEXT,
    notes TEXT,
    completed_at TEXT,
    created_by INTEGER,
    created_at TEXT NOT NULL,
    hr_activity_id INTEGER
);

CREATE TABLE IF NOT EXISTS recruitment_offers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    applicant_id INTEGER NOT NULL,
    offer_number TEXT,
    status TEXT NOT NULL DEFAULT 'Draft',
    contract_type TEXT NOT NULL DEFAULT 'Permanent',
    job_title TEXT,
    department_id INTEGER,
    start_date TEXT NOT NULL,
    end_date TEXT,
    probation_months INTEGER NOT NULL DEFAULT 3,
    probation_end_date TEXT,
    work_schedule TEXT,
    weekly_hours DOUBLE PRECISION DEFAULT 48,
    annual_leave_days INTEGER NOT NULL DEFAULT 15,
    notice_period_days INTEGER NOT NULL DEFAULT 30,
    salary DOUBLE PRECISION NOT NULL DEFAULT 0,
    salary_currency TEXT NOT NULL DEFAULT 'USD',
    payment_schedule TEXT NOT NULL DEFAULT 'Monthly',
    include_nssf INTEGER NOT NULL DEFAULT 1,
    include_eos INTEGER NOT NULL DEFAULT 1,
    include_confidentiality INTEGER NOT NULL DEFAULT 1,
    include_non_compete INTEGER NOT NULL DEFAULT 0,
    non_compete_months INTEGER NOT NULL DEFAULT 6,
    benefits TEXT,
    additional_terms TEXT,
    place_of_work TEXT,
    sent_at TEXT,
    accepted_at TEXT,
    declined_at TEXT,
    declined_reason TEXT,
    expires_at TEXT,
    created_by INTEGER,
    created_at TEXT NOT NULL,
    updated_at TEXT,
    archived_at TEXT
);

CREATE TABLE IF NOT EXISTS recruitment_positions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    department_id INTEGER,
    employment_type TEXT NOT NULL DEFAULT 'Full-time',
    location TEXT,
    salary_min DOUBLE PRECISION,
    salary_max DOUBLE PRECISION,
    headcount INTEGER NOT NULL DEFAULT 1,
    status TEXT NOT NULL DEFAULT 'Open',
    description TEXT,
    requirements TEXT,
    posted_at TEXT,
    closed_at TEXT,
    created_by INTEGER,
    archived_at TEXT,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS recruitment_status_history (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    applicant_id INTEGER NOT NULL,
    old_status TEXT,
    new_status TEXT NOT NULL,
    note TEXT,
    changed_by INTEGER,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS recurring_expenses (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    description TEXT,
    amount DOUBLE PRECISION NOT NULL DEFAULT 0,
    frequency TEXT NOT NULL DEFAULT 'monthly',
    start_date TEXT NOT NULL,
    end_date TEXT,
    next_run_date TEXT NOT NULL,
    last_generated_date TEXT,
    project_id INTEGER,
    payment_method TEXT,
    tax_rate_id INTEGER,
    is_active INTEGER NOT NULL DEFAULT 1,
    archived_at TEXT,
    created_by INTEGER,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS role_permissions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id INTEGER NOT NULL,
    module TEXT NOT NULL,
    can_view INTEGER DEFAULT 0,
    can_create INTEGER DEFAULT 0,
    can_edit INTEGER DEFAULT 0,
    can_delete INTEGER DEFAULT 0,
    can_approve INTEGER DEFAULT 0,
    UNIQUE (role_id, module)
);

CREATE TABLE IF NOT EXISTS roles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    color TEXT DEFAULT '#6B7280',
    is_system INTEGER DEFAULT 0,
    is_admin INTEGER DEFAULT 0,
    created_at TEXT NOT NULL,
    UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS schema_migrations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    applied_at TEXT NOT NULL,
    UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS settings (
    key TEXT,
    value TEXT,
    PRIMARY KEY (key)
);

CREATE TABLE IF NOT EXISTS stock_movements (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_id INTEGER NOT NULL,
    type TEXT NOT NULL,
    delta DOUBLE PRECISION NOT NULL,
    qty_before DOUBLE PRECISION NOT NULL,
    qty_after DOUBLE PRECISION NOT NULL,
    reference TEXT,
    note TEXT,
    created_at TEXT,
    warehouse_id INTEGER
);

CREATE TABLE IF NOT EXISTS stock_transfer_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transfer_id INTEGER NOT NULL,
    inventory_id INTEGER NOT NULL,
    quantity DOUBLE PRECISION NOT NULL,
    received_quantity DOUBLE PRECISION,
    note TEXT
);

CREATE TABLE IF NOT EXISTS stock_transfers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transfer_number TEXT NOT NULL,
    from_warehouse_id INTEGER NOT NULL,
    to_warehouse_id INTEGER NOT NULL,
    status TEXT NOT NULL DEFAULT 'Draft',
    notes TEXT,
    created_by INTEGER,
    created_at TEXT NOT NULL,
    dispatched_by INTEGER,
    dispatched_at TEXT,
    received_by INTEGER,
    received_at TEXT,
    cancelled_by INTEGER,
    cancelled_at TEXT,
    cancel_reason TEXT,
    UNIQUE (transfer_number)
);

CREATE TABLE IF NOT EXISTS suppliers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    contact_name TEXT,
    phone TEXT,
    email TEXT,
    payment_terms_days INTEGER DEFAULT 30,
    notes TEXT,
    deleted_at TEXT,
    created_at TEXT NOT NULL,
    archived_at TEXT DEFAULT NULL,
    archive_reason TEXT DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS tax_rates (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    rate DOUBLE PRECISION NOT NULL DEFAULT 0,
    tax_type TEXT NOT NULL DEFAULT 'standard',
    is_default INTEGER NOT NULL DEFAULT 0,
    is_active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS user_sessions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    jti TEXT NOT NULL,
    ip_address TEXT,
    user_agent TEXT,
    created_at TEXT NOT NULL,
    last_active TEXT NOT NULL,
    expires_at TEXT NOT NULL,
    revoked INTEGER DEFAULT 0,
    UNIQUE (jti)
);

CREATE TABLE IF NOT EXISTS user_warehouse_access (
    user_id INTEGER NOT NULL,
    warehouse_id INTEGER NOT NULL,
    granted_at TEXT NOT NULL,
    granted_by INTEGER,
    PRIMARY KEY (user_id, warehouse_id)
);

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    full_name TEXT,
    role TEXT DEFAULT 'admin',
    created_at TEXT,
    email TEXT,
    is_active INTEGER DEFAULT 1,
    is_superadmin INTEGER DEFAULT 0,
    role_id INTEGER,
    last_login TEXT,
    deleted_at TEXT,
    must_change_password INTEGER NOT NULL DEFAULT 0,
    default_warehouse_id INTEGER,
    UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS warehouses (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    type TEXT NOT NULL DEFAULT 'Main',
    address TEXT,
    manager_id INTEGER,
    is_active INTEGER NOT NULL DEFAULT 1,
    is_default INTEGER NOT NULL DEFAULT 0,
    notes TEXT,
    archived_at TEXT,
    archive_reason TEXT,
    created_at TEXT NOT NULL,
    UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS work_centers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT,
    name TEXT NOT NULL,
    type TEXT NOT NULL DEFAULT 'Machine',
    labor_rate DOUBLE PRECISION NOT NULL DEFAULT 0,
    machine_rate DOUBLE PRECISION NOT NULL DEFAULT 0,
    overhead_rate DOUBLE PRECISION NOT NULL DEFAULT 0,
    power_kw DOUBLE PRECISION NOT NULL DEFAULT 0,
    is_active INTEGER NOT NULL DEFAULT 1,
    notes TEXT,
    archived_at TEXT,
    created_at TEXT NOT NULL,
    UNIQUE (code)
);

-- ── Seed / reference data (migration-inserted rows) ──────────────────────
INSERT INTO cash_drawers (id, name, is_active, auto_capture, created_at) VALUES
    (1, 'Main Till', 1, 1, '2026-06-05 01:21:31')
ON CONFLICT DO NOTHING;
INSERT INTO chart_of_accounts (id, code, name, type, subtype, normal_balance, parent_code, is_system, is_active, description, created_at) VALUES
    (1, '1000', 'Cash & Bank', 'Asset', 'Current Asset', 'debit', NULL, 1, 1, NULL, '2026-06-05 01:21:31'),
    (2, '1100', 'Accounts Receivable', 'Asset', 'Current Asset', 'debit', NULL, 1, 1, NULL, '2026-06-05 01:21:31'),
    (3, '1200', 'Inventory', 'Asset', 'Current Asset', 'debit', NULL, 1, 1, NULL, '2026-06-05 01:21:31'),
    (4, '1500', 'Fixed Assets', 'Asset', 'Non-Current Asset', 'debit', NULL, 1, 1, NULL, '2026-06-05 01:21:31'),
    (5, '1510', 'Accumulated Depreciation', 'Asset', 'Contra Asset', 'credit', NULL, 1, 1, NULL, '2026-06-05 01:21:31'),
    (6, '2000', 'Accounts Payable', 'Liability', 'Current Liability', 'credit', NULL, 1, 1, NULL, '2026-06-05 01:21:31'),
    (7, '2100', 'VAT Payable', 'Liability', 'Current Liability', 'credit', NULL, 1, 1, NULL, '2026-06-05 01:21:31'),
    (8, '2200', 'Payroll Liabilities', 'Liability', 'Current Liability', 'credit', NULL, 1, 1, NULL, '2026-06-05 01:21:31'),
    (9, '3000', 'Owner''s Equity', 'Equity', 'Equity', 'credit', NULL, 1, 1, NULL, '2026-06-05 01:21:31'),
    (10, '3900', 'Retained Earnings', 'Equity', 'Equity', 'credit', NULL, 1, 1, NULL, '2026-06-05 01:21:31'),
    (11, '4000', 'Sales Revenue', 'Income', 'Operating Income', 'credit', NULL, 1, 1, NULL, '2026-06-05 01:21:31'),
    (12, '4900', 'Other Income', 'Income', 'Other Income', 'credit', NULL, 1, 1, NULL, '2026-06-05 01:21:31'),
    (13, '5000', 'Cost of Goods Sold', 'Expense', 'Cost of Sales', 'debit', NULL, 1, 1, NULL, '2026-06-05 01:21:31'),
    (14, '6000', 'Salaries & Wages', 'Expense', 'Operating Expense', 'debit', NULL, 1, 1, NULL, '2026-06-05 01:21:31'),
    (15, '6100', 'Rent', 'Expense', 'Operating Expense', 'debit', NULL, 1, 1, NULL, '2026-06-05 01:21:31'),
    (16, '6200', 'Utilities', 'Expense', 'Operating Expense', 'debit', NULL, 1, 1, NULL, '2026-06-05 01:21:31'),
    (17, '6300', 'Depreciation Expense', 'Expense', 'Operating Expense', 'debit', NULL, 1, 1, NULL, '2026-06-05 01:21:31'),
    (18, '6400', 'Materials', 'Expense', 'Operating Expense', 'debit', NULL, 1, 1, NULL, '2026-06-05 01:21:31'),
    (19, '6500', 'Labour', 'Expense', 'Operating Expense', 'debit', NULL, 1, 1, NULL, '2026-06-05 01:21:31'),
    (20, '6600', 'Equipment', 'Expense', 'Operating Expense', 'debit', NULL, 1, 1, NULL, '2026-06-05 01:21:31'),
    (21, '6700', 'Transport', 'Expense', 'Operating Expense', 'debit', NULL, 1, 1, NULL, '2026-06-05 01:21:31'),
    (22, '6800', 'Subcontractor', 'Expense', 'Operating Expense', 'debit', NULL, 1, 1, NULL, '2026-06-05 01:21:31'),
    (23, '6850', 'Insurance', 'Expense', 'Operating Expense', 'debit', NULL, 1, 1, NULL, '2026-06-05 01:21:31'),
    (24, '6860', 'Subscriptions', 'Expense', 'Operating Expense', 'debit', NULL, 1, 1, NULL, '2026-06-05 01:21:31'),
    (25, '6870', 'Permits & Fees', 'Expense', 'Operating Expense', 'debit', NULL, 1, 1, NULL, '2026-06-05 01:21:31'),
    (26, '6900', 'General & Other Expense', 'Expense', 'Operating Expense', 'debit', NULL, 1, 1, NULL, '2026-06-05 01:21:31'),
    (27, '1010', 'Cash — LBP', 'Asset', 'Current Asset', 'debit', NULL, 1, 1, NULL, '2026-06-05 01:21:31'),
    (28, '4910', 'Foreign Exchange Gain', 'Income', 'Other Income', 'credit', NULL, 1, 1, NULL, '2026-06-05 01:21:31'),
    (29, '6910', 'Cash Short & Over', 'Expense', 'Operating Expense', 'debit', NULL, 1, 1, NULL, '2026-06-05 01:21:31'),
    (30, '6920', 'Foreign Exchange Loss', 'Expense', 'Other Expense', 'debit', NULL, 1, 1, NULL, '2026-06-05 01:21:31')
ON CONFLICT DO NOTHING;
INSERT INTO tax_rates (id, name, rate, tax_type, is_default, is_active, created_at) VALUES
    (1, 'VAT 11%', 11.0, 'standard', 1, 1, '2026-06-05 01:21:31'),
    (2, 'Zero-rated', 0.0, 'zero', 0, 1, '2026-06-05 01:21:31'),
    (3, 'Exempt', 0.0, 'exempt', 0, 1, '2026-06-05 01:21:31')
ON CONFLICT DO NOTHING;
INSERT INTO warehouses (id, code, name, type, address, manager_id, is_active, is_default, notes, archived_at, archive_reason, created_at) VALUES
    (1, 'MAIN', 'Main Warehouse', 'Main', NULL, NULL, 1, 1, 'Default warehouse, auto-created during multi-warehouse migration.', NULL, NULL, '2026-06-05 01:21:31')
ON CONFLICT DO NOTHING;

-- Advance identity sequences past the seeded ids.
SELECT setval(pg_get_serial_sequence('cash_drawers', 'id'), (SELECT COALESCE(MAX(id), 1) FROM cash_drawers));
SELECT setval(pg_get_serial_sequence('chart_of_accounts', 'id'), (SELECT COALESCE(MAX(id), 1) FROM chart_of_accounts));
SELECT setval(pg_get_serial_sequence('tax_rates', 'id'), (SELECT COALESCE(MAX(id), 1) FROM tax_rates));
SELECT setval(pg_get_serial_sequence('warehouses', 'id'), (SELECT COALESCE(MAX(id), 1) FROM warehouses));

-- ── Foreign keys (added after all tables exist) ──────────────────────────
ALTER TABLE announcement_comments ADD FOREIGN KEY (author_id) REFERENCES users (id);
ALTER TABLE announcement_comments ADD FOREIGN KEY (announcement_id) REFERENCES announcements (id);
ALTER TABLE announcement_recipients ADD FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE announcement_recipients ADD FOREIGN KEY (announcement_id) REFERENCES announcements (id);
ALTER TABLE approval_comments ADD FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE approval_comments ADD FOREIGN KEY (request_id) REFERENCES approval_requests (id) ON DELETE CASCADE;
ALTER TABLE approval_policies ADD FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE approval_requests ADD FOREIGN KEY (resolved_by) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE approval_requests ADD FOREIGN KEY (requested_by) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE approval_requests ADD FOREIGN KEY (policy_id) REFERENCES approval_policies (id) ON DELETE SET NULL;
ALTER TABLE approval_steps ADD FOREIGN KEY (approver_user_id) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE approval_steps ADD FOREIGN KEY (request_id) REFERENCES approval_requests (id) ON DELETE CASCADE;
ALTER TABLE asset_depreciation ADD FOREIGN KEY (posted_by) REFERENCES users (id);
ALTER TABLE asset_depreciation ADD FOREIGN KEY (expense_id) REFERENCES expenses (id);
ALTER TABLE asset_depreciation ADD FOREIGN KEY (asset_id) REFERENCES fixed_assets (id) ON DELETE CASCADE;
ALTER TABLE attachments ADD FOREIGN KEY (uploaded_by) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE bom_components ADD FOREIGN KEY (component_inventory_id) REFERENCES inventory (id);
ALTER TABLE bom_components ADD FOREIGN KEY (bom_id) REFERENCES boms (id) ON DELETE CASCADE;
ALTER TABLE bom_operations ADD FOREIGN KEY (work_center_id) REFERENCES work_centers (id) ON DELETE SET NULL;
ALTER TABLE bom_operations ADD FOREIGN KEY (bom_id) REFERENCES boms (id) ON DELETE CASCADE;
ALTER TABLE bom_resources ADD FOREIGN KEY (resource_id) REFERENCES manufacturing_resources (id) ON DELETE SET NULL;
ALTER TABLE bom_resources ADD FOREIGN KEY (bom_id) REFERENCES boms (id) ON DELETE CASCADE;
ALTER TABLE boms ADD FOREIGN KEY (output_inventory_id) REFERENCES inventory (id);
ALTER TABLE cash_movements ADD FOREIGN KEY (created_by) REFERENCES users (id);
ALTER TABLE cash_movements ADD FOREIGN KEY (reconciliation_id) REFERENCES cash_reconciliations (id) ON DELETE CASCADE;
ALTER TABLE cash_reconciliations ADD FOREIGN KEY (closed_by) REFERENCES users (id);
ALTER TABLE cash_reconciliations ADD FOREIGN KEY (opened_by) REFERENCES users (id);
ALTER TABLE cash_reconciliations ADD FOREIGN KEY (drawer_id) REFERENCES cash_drawers (id);
ALTER TABLE crm_activities ADD FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE crm_activities ADD FOREIGN KEY (contact_id) REFERENCES crm_contacts (id);
ALTER TABLE crm_activities ADD FOREIGN KEY (lead_id) REFERENCES crm_leads (id);
ALTER TABLE crm_activities ADD FOREIGN KEY (client_id) REFERENCES clients (id);
ALTER TABLE crm_contacts ADD FOREIGN KEY (lead_id) REFERENCES crm_leads (id);
ALTER TABLE crm_contacts ADD FOREIGN KEY (client_id) REFERENCES clients (id);
ALTER TABLE crm_deals ADD FOREIGN KEY (assigned_to) REFERENCES users (id);
ALTER TABLE crm_deals ADD FOREIGN KEY (quotation_id) REFERENCES quotations (id);
ALTER TABLE crm_deals ADD FOREIGN KEY (lead_id) REFERENCES crm_leads (id);
ALTER TABLE crm_deals ADD FOREIGN KEY (client_id) REFERENCES clients (id);
ALTER TABLE crm_leads ADD FOREIGN KEY (client_id) REFERENCES clients (id);
ALTER TABLE crm_leads ADD FOREIGN KEY (assigned_to) REFERENCES users (id);
ALTER TABLE exchange_rates ADD FOREIGN KEY (set_by) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE expenses ADD FOREIGN KEY (fixed_asset_id) REFERENCES fixed_assets (id);
ALTER TABLE expenses ADD FOREIGN KEY (recurring_expense_id) REFERENCES recurring_expenses (id);
ALTER TABLE expenses ADD FOREIGN KEY (project_id) REFERENCES projects (id);
ALTER TABLE fiscal_years ADD FOREIGN KEY (closed_by) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE fiscal_years ADD FOREIGN KEY (closing_entry_id) REFERENCES journal_entries (id) ON DELETE SET NULL;
ALTER TABLE fixed_assets ADD FOREIGN KEY (created_by) REFERENCES users (id);
ALTER TABLE fixed_assets ADD FOREIGN KEY (supplier_id) REFERENCES suppliers (id);
ALTER TABLE hr_activities ADD FOREIGN KEY (reminder_notif_id) REFERENCES notifications (id) ON DELETE SET NULL;
ALTER TABLE hr_activities ADD FOREIGN KEY (employee_id) REFERENCES hr_employees (id) ON DELETE SET NULL;
ALTER TABLE hr_activities ADD FOREIGN KEY (applicant_id) REFERENCES recruitment_applicants (id) ON DELETE SET NULL;
ALTER TABLE hr_activities ADD FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE hr_contracts ADD FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE hr_contracts ADD FOREIGN KEY (employee_id) REFERENCES hr_employees (id) ON DELETE CASCADE;
ALTER TABLE hr_employee_files ADD FOREIGN KEY (uploaded_by) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE hr_employee_files ADD FOREIGN KEY (employee_id) REFERENCES hr_employees (id) ON DELETE CASCADE;
ALTER TABLE hr_employees ADD FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE hr_employees ADD FOREIGN KEY (manager_id) REFERENCES hr_employees (id) ON DELETE SET NULL;
ALTER TABLE hr_employees ADD FOREIGN KEY (department_id) REFERENCES hr_departments (id) ON DELETE SET NULL;
ALTER TABLE hr_employment_changes ADD FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE hr_employment_changes ADD FOREIGN KEY (new_manager_id) REFERENCES hr_employees (id) ON DELETE SET NULL;
ALTER TABLE hr_employment_changes ADD FOREIGN KEY (old_manager_id) REFERENCES hr_employees (id) ON DELETE SET NULL;
ALTER TABLE hr_employment_changes ADD FOREIGN KEY (new_department_id) REFERENCES hr_departments (id) ON DELETE SET NULL;
ALTER TABLE hr_employment_changes ADD FOREIGN KEY (old_department_id) REFERENCES hr_departments (id) ON DELETE SET NULL;
ALTER TABLE hr_employment_changes ADD FOREIGN KEY (employee_id) REFERENCES hr_employees (id) ON DELETE CASCADE;
ALTER TABLE hr_leave_requests ADD FOREIGN KEY (reviewed_by) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE hr_leave_requests ADD FOREIGN KEY (employee_id) REFERENCES hr_employees (id) ON DELETE CASCADE;
ALTER TABLE hr_payroll_lines ADD FOREIGN KEY (employee_id) REFERENCES hr_employees (id) ON DELETE RESTRICT;
ALTER TABLE hr_payroll_lines ADD FOREIGN KEY (payroll_run_id) REFERENCES hr_payroll_runs (id) ON DELETE CASCADE;
ALTER TABLE hr_payroll_runs ADD FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE hr_payroll_runs ADD FOREIGN KEY (paid_by) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE hr_payroll_runs ADD FOREIGN KEY (approved_by) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE hr_payroll_runs ADD FOREIGN KEY (posted_expense_id) REFERENCES expenses (id) ON DELETE SET NULL;
ALTER TABLE inventory_cost_layers ADD FOREIGN KEY (inventory_id) REFERENCES inventory (id) ON DELETE CASCADE;
ALTER TABLE inventory_lots ADD FOREIGN KEY (inventory_id) REFERENCES inventory (id) ON DELETE CASCADE;
ALTER TABLE inventory_stock ADD FOREIGN KEY (warehouse_id) REFERENCES warehouses (id);
ALTER TABLE inventory_stock ADD FOREIGN KEY (inventory_id) REFERENCES inventory (id) ON DELETE CASCADE;
ALTER TABLE invoice_items ADD FOREIGN KEY (invoice_id) REFERENCES invoices (id) ON DELETE CASCADE;
ALTER TABLE invoice_payments ADD FOREIGN KEY (invoice_id) REFERENCES invoices (id) ON DELETE CASCADE;
ALTER TABLE invoices ADD FOREIGN KEY (client_id) REFERENCES clients (id);
ALTER TABLE invoices ADD FOREIGN KEY (project_id) REFERENCES projects (id);
ALTER TABLE invoices ADD FOREIGN KEY (quotation_id) REFERENCES quotations (id);
ALTER TABLE journal_entries ADD FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE journal_entries ADD FOREIGN KEY (reversed_by) REFERENCES journal_entries (id) ON DELETE SET NULL;
ALTER TABLE journal_entries ADD FOREIGN KEY (reverses_id) REFERENCES journal_entries (id) ON DELETE SET NULL;
ALTER TABLE journal_entry_lines ADD FOREIGN KEY (account_id) REFERENCES chart_of_accounts (id);
ALTER TABLE journal_entry_lines ADD FOREIGN KEY (journal_entry_id) REFERENCES journal_entries (id) ON DELETE CASCADE;
ALTER TABLE lot_consumption ADD FOREIGN KEY (output_lot_id) REFERENCES inventory_lots (id) ON DELETE SET NULL;
ALTER TABLE lot_consumption ADD FOREIGN KEY (production_order_id) REFERENCES production_orders (id) ON DELETE SET NULL;
ALTER TABLE lot_consumption ADD FOREIGN KEY (inventory_id) REFERENCES inventory (id);
ALTER TABLE lot_consumption ADD FOREIGN KEY (lot_id) REFERENCES inventory_lots (id) ON DELETE CASCADE;
ALTER TABLE notifications ADD FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE planning_milestones ADD FOREIGN KEY (project_id) REFERENCES planning_projects (id) ON DELETE CASCADE;
ALTER TABLE planning_projects ADD FOREIGN KEY (created_by) REFERENCES users (id);
ALTER TABLE planning_projects ADD FOREIGN KEY (client_id) REFERENCES clients (id);
ALTER TABLE planning_tasks ADD FOREIGN KEY (depends_on) REFERENCES planning_tasks (id);
ALTER TABLE planning_tasks ADD FOREIGN KEY (milestone_id) REFERENCES planning_milestones (id);
ALTER TABLE planning_tasks ADD FOREIGN KEY (assigned_to) REFERENCES users (id);
ALTER TABLE planning_tasks ADD FOREIGN KEY (project_id) REFERENCES planning_projects (id) ON DELETE CASCADE;
ALTER TABLE pos_returns ADD FOREIGN KEY (cashier_id) REFERENCES users (id);
ALTER TABLE pos_returns ADD FOREIGN KEY (invoice_id) REFERENCES invoices (id);
ALTER TABLE pos_returns ADD FOREIGN KEY (session_id) REFERENCES pos_sessions (id);
ALTER TABLE pos_returns ADD FOREIGN KEY (pos_sale_id) REFERENCES pos_sales (id);
ALTER TABLE pos_sale_items ADD FOREIGN KEY (inventory_id) REFERENCES inventory (id);
ALTER TABLE pos_sale_items ADD FOREIGN KEY (invoice_item_id) REFERENCES invoice_items (id) ON DELETE SET NULL;
ALTER TABLE pos_sale_items ADD FOREIGN KEY (pos_sale_id) REFERENCES pos_sales (id) ON DELETE CASCADE;
ALTER TABLE pos_sales ADD FOREIGN KEY (cashier_id) REFERENCES users (id);
ALTER TABLE pos_sales ADD FOREIGN KEY (invoice_id) REFERENCES invoices (id) ON DELETE CASCADE;
ALTER TABLE pos_sales ADD FOREIGN KEY (session_id) REFERENCES pos_sessions (id);
ALTER TABLE pos_sessions ADD FOREIGN KEY (warehouse_id) REFERENCES warehouses (id);
ALTER TABLE pos_sessions ADD FOREIGN KEY (cashier_id) REFERENCES users (id);
ALTER TABLE production_order_items ADD FOREIGN KEY (component_inventory_id) REFERENCES inventory (id);
ALTER TABLE production_order_items ADD FOREIGN KEY (production_order_id) REFERENCES production_orders (id) ON DELETE CASCADE;
ALTER TABLE production_order_operations ADD FOREIGN KEY (work_center_id) REFERENCES work_centers (id) ON DELETE SET NULL;
ALTER TABLE production_order_operations ADD FOREIGN KEY (production_order_id) REFERENCES production_orders (id) ON DELETE CASCADE;
ALTER TABLE production_order_resources ADD FOREIGN KEY (resource_id) REFERENCES manufacturing_resources (id) ON DELETE SET NULL;
ALTER TABLE production_order_resources ADD FOREIGN KEY (production_order_id) REFERENCES production_orders (id) ON DELETE CASCADE;
ALTER TABLE production_orders ADD FOREIGN KEY (warehouse_id) REFERENCES warehouses (id);
ALTER TABLE production_orders ADD FOREIGN KEY (created_by) REFERENCES users (id);
ALTER TABLE production_orders ADD FOREIGN KEY (output_inventory_id) REFERENCES inventory (id);
ALTER TABLE production_orders ADD FOREIGN KEY (bom_id) REFERENCES boms (id);
ALTER TABLE production_qc ADD FOREIGN KEY (inspector_id) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE production_qc ADD FOREIGN KEY (output_inventory_id) REFERENCES inventory (id);
ALTER TABLE production_qc ADD FOREIGN KEY (production_order_id) REFERENCES production_orders (id) ON DELETE CASCADE;
ALTER TABLE production_qc_defects ADD FOREIGN KEY (qc_id) REFERENCES production_qc (id) ON DELETE CASCADE;
ALTER TABLE projects ADD FOREIGN KEY (source_quotation_id) REFERENCES quotations (id);
ALTER TABLE projects ADD FOREIGN KEY (client_id) REFERENCES clients (id);
ALTER TABLE purchases ADD FOREIGN KEY (warehouse_id) REFERENCES warehouses (id);
ALTER TABLE purchases ADD FOREIGN KEY (inventory_id) REFERENCES inventory (id);
ALTER TABLE purchases ADD FOREIGN KEY (supplier_id) REFERENCES suppliers (id);
ALTER TABLE quotation_items ADD FOREIGN KEY (quotation_id) REFERENCES quotations (id) ON DELETE CASCADE;
ALTER TABLE quotations ADD FOREIGN KEY (lead_id) REFERENCES crm_leads (id);
ALTER TABLE quotations ADD FOREIGN KEY (client_id) REFERENCES clients (id);
ALTER TABLE quotations ADD FOREIGN KEY (project_id) REFERENCES projects (id);
ALTER TABLE recruitment_applicant_files ADD FOREIGN KEY (uploaded_by) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE recruitment_applicant_files ADD FOREIGN KEY (applicant_id) REFERENCES recruitment_applicants (id) ON DELETE CASCADE;
ALTER TABLE recruitment_applicants ADD FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE recruitment_applicants ADD FOREIGN KEY (converted_employee_id) REFERENCES hr_employees (id) ON DELETE SET NULL;
ALTER TABLE recruitment_applicants ADD FOREIGN KEY (assigned_to) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE recruitment_applicants ADD FOREIGN KEY (position_id) REFERENCES recruitment_positions (id) ON DELETE SET NULL;
ALTER TABLE recruitment_interviews ADD FOREIGN KEY (hr_activity_id) REFERENCES hr_activities (id) ON DELETE SET NULL;
ALTER TABLE recruitment_interviews ADD FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE recruitment_interviews ADD FOREIGN KEY (interviewer_id) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE recruitment_interviews ADD FOREIGN KEY (applicant_id) REFERENCES recruitment_applicants (id) ON DELETE CASCADE;
ALTER TABLE recruitment_offers ADD FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE recruitment_offers ADD FOREIGN KEY (department_id) REFERENCES hr_departments (id) ON DELETE SET NULL;
ALTER TABLE recruitment_offers ADD FOREIGN KEY (applicant_id) REFERENCES recruitment_applicants (id) ON DELETE CASCADE;
ALTER TABLE recruitment_positions ADD FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE recruitment_positions ADD FOREIGN KEY (department_id) REFERENCES hr_departments (id) ON DELETE SET NULL;
ALTER TABLE recruitment_status_history ADD FOREIGN KEY (changed_by) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE recruitment_status_history ADD FOREIGN KEY (applicant_id) REFERENCES recruitment_applicants (id) ON DELETE CASCADE;
ALTER TABLE recurring_expenses ADD FOREIGN KEY (created_by) REFERENCES users (id);
ALTER TABLE recurring_expenses ADD FOREIGN KEY (tax_rate_id) REFERENCES tax_rates (id);
ALTER TABLE recurring_expenses ADD FOREIGN KEY (project_id) REFERENCES projects (id);
ALTER TABLE role_permissions ADD FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE;
ALTER TABLE stock_movements ADD FOREIGN KEY (warehouse_id) REFERENCES warehouses (id);
ALTER TABLE stock_movements ADD FOREIGN KEY (inventory_id) REFERENCES inventory (id) ON DELETE CASCADE;
ALTER TABLE stock_transfer_items ADD FOREIGN KEY (inventory_id) REFERENCES inventory (id);
ALTER TABLE stock_transfer_items ADD FOREIGN KEY (transfer_id) REFERENCES stock_transfers (id) ON DELETE CASCADE;
ALTER TABLE stock_transfers ADD FOREIGN KEY (cancelled_by) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE stock_transfers ADD FOREIGN KEY (received_by) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE stock_transfers ADD FOREIGN KEY (dispatched_by) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE stock_transfers ADD FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE stock_transfers ADD FOREIGN KEY (to_warehouse_id) REFERENCES warehouses (id);
ALTER TABLE stock_transfers ADD FOREIGN KEY (from_warehouse_id) REFERENCES warehouses (id);
ALTER TABLE user_sessions ADD FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE user_warehouse_access ADD FOREIGN KEY (granted_by) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE user_warehouse_access ADD FOREIGN KEY (warehouse_id) REFERENCES warehouses (id) ON DELETE CASCADE;
ALTER TABLE user_warehouse_access ADD FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE users ADD FOREIGN KEY (default_warehouse_id) REFERENCES warehouses (id);
ALTER TABLE users ADD FOREIGN KEY (role_id) REFERENCES roles (id);
ALTER TABLE warehouses ADD FOREIGN KEY (manager_id) REFERENCES users (id) ON DELETE SET NULL;

-- ── Indexes ──────────────────────────────────────────────────────────────
CREATE INDEX idx_ann_archived   ON announcements(archived_at);
CREATE INDEX idx_ann_cmt_ann    ON announcement_comments(announcement_id);
CREATE INDEX idx_ann_pub        ON announcements(published_at);
CREATE INDEX idx_ann_rec_ann    ON announcement_recipients(announcement_id);
CREATE INDEX idx_ann_rec_user   ON announcement_recipients(user_id);
CREATE INDEX idx_appcomment_request ON approval_comments(request_id);
CREATE INDEX idx_appreq_module ON approval_requests(module, entity_id);
CREATE INDEX idx_appreq_req_by ON approval_requests(requested_by);
CREATE INDEX idx_appreq_status ON approval_requests(status);
CREATE INDEX idx_appstep_req_step ON approval_steps(request_id, step_number);
CREATE INDEX idx_appstep_request ON approval_steps(request_id);
CREATE INDEX idx_asset_depreciation_asset ON asset_depreciation(asset_id);
CREATE INDEX idx_attachments_entity ON attachments(entity_type, entity_id, created_at);
CREATE INDEX idx_audit_log_action      ON audit_log(action);
CREATE INDEX idx_audit_log_created_at  ON audit_log(created_at);
CREATE INDEX idx_audit_log_module      ON audit_log(module);
CREATE INDEX idx_audit_log_username    ON audit_log(username);
CREATE INDEX idx_bom_components_bom ON bom_components(bom_id);
CREATE INDEX idx_bom_operations_bom ON bom_operations(bom_id);
CREATE INDEX idx_bom_resources_bom ON bom_resources(bom_id);
CREATE INDEX idx_boms_output ON boms(output_inventory_id);
CREATE INDEX idx_cash_movements_recon ON cash_movements(reconciliation_id);
CREATE INDEX idx_cash_recon_drawer ON cash_reconciliations(drawer_id, business_date);
CREATE INDEX idx_cost_layers_item ON inventory_cost_layers(inventory_id, created_at, id);
CREATE INDEX idx_crm_activities_client   ON crm_activities(client_id);
CREATE INDEX idx_crm_activities_due_date ON crm_activities(due_date);
CREATE INDEX idx_crm_activities_lead     ON crm_activities(lead_id);
CREATE INDEX idx_crm_contacts_client ON crm_contacts(client_id);
CREATE INDEX idx_crm_contacts_lead   ON crm_contacts(lead_id);
CREATE INDEX idx_crm_deals_client_id ON crm_deals(client_id);
CREATE INDEX idx_crm_deals_lead_id   ON crm_deals(lead_id);
CREATE INDEX idx_crm_deals_stage     ON crm_deals(stage);
CREATE INDEX idx_crm_leads_client_id ON crm_leads(client_id);
CREATE INDEX idx_crm_leads_status    ON crm_leads(status);
CREATE INDEX idx_documents_client  ON documents(client_id);
CREATE INDEX idx_documents_project ON documents(project_id);
CREATE INDEX idx_documents_record  ON documents(record_type, record_id);
CREATE INDEX idx_exchange_rates_created ON exchange_rates(created_at);
CREATE INDEX idx_expenses_project_id   ON expenses(project_id);
CREATE INDEX idx_fixed_assets_status ON fixed_assets(status);
CREATE INDEX idx_hr_activities_applicant ON hr_activities(applicant_id);
CREATE INDEX idx_hr_activities_employee ON hr_activities(employee_id);
CREATE INDEX idx_hr_activities_owner_sched ON hr_activities(owner_id, scheduled_at);
CREATE INDEX idx_hr_contracts_emp ON hr_contracts(employee_id);
CREATE INDEX idx_hr_contracts_status ON hr_contracts(status);
CREATE INDEX idx_hr_dept_archived ON hr_departments(archived_at);
CREATE INDEX idx_hr_emp_archived ON hr_employees(archived_at);
CREATE INDEX idx_hr_emp_changes_date ON hr_employment_changes(effective_date);
CREATE INDEX idx_hr_emp_changes_emp ON hr_employment_changes(employee_id);
CREATE INDEX idx_hr_emp_dept     ON hr_employees(department_id);
CREATE INDEX idx_hr_emp_files_emp ON hr_employee_files(employee_id);
CREATE INDEX idx_hr_emp_status   ON hr_employees(status);
CREATE INDEX idx_hr_leave_emp    ON hr_leave_requests(employee_id);
CREATE INDEX idx_hr_leave_status ON hr_leave_requests(status);
CREATE INDEX idx_hr_payroll_lines_emp ON hr_payroll_lines(employee_id);
CREATE INDEX idx_hr_payroll_lines_run ON hr_payroll_lines(payroll_run_id);
CREATE INDEX idx_hr_payroll_runs_period ON hr_payroll_runs(period_start, period_end);
CREATE INDEX idx_hr_payroll_runs_status ON hr_payroll_runs(status);
CREATE INDEX idx_inv_stock_warehouse ON inventory_stock(warehouse_id);
CREATE INDEX idx_inventory_barcode ON inventory(barcode);
CREATE INDEX idx_invoice_items_inv     ON invoice_items(invoice_id);
CREATE INDEX idx_invoice_payments_inv  ON invoice_payments(invoice_id);
CREATE INDEX idx_invoices_client_id    ON invoices(client_id);
CREATE INDEX idx_invoices_project_id   ON invoices(project_id);
CREATE INDEX idx_je_date   ON journal_entries(entry_date);
CREATE INDEX idx_je_source ON journal_entries(source_type, source_id);
CREATE INDEX idx_jel_acct  ON journal_entry_lines(account_id);
CREATE INDEX idx_jel_entry ON journal_entry_lines(journal_entry_id);
CREATE INDEX idx_login_attempts_ip     ON login_attempts(ip, attempted_at);
CREATE INDEX idx_lotcons_lot    ON lot_consumption(lot_id);
CREATE INDEX idx_lotcons_order  ON lot_consumption(production_order_id);
CREATE INDEX idx_lotcons_output ON lot_consumption(output_lot_id);
CREATE INDEX idx_lots_expiry ON inventory_lots(expiry_date);
CREATE INDEX idx_lots_item   ON inventory_lots(inventory_id, status);
CREATE INDEX idx_notifications_created ON notifications(created_at);
CREATE INDEX idx_notifications_type    ON notifications(type);
CREATE INDEX idx_notifications_user    ON notifications(user_id, is_read);
CREATE UNIQUE INDEX idx_payments_idempotency
            ON invoice_payments(idempotency_key) WHERE idempotency_key IS NOT NULL;
CREATE INDEX idx_planning_events_owner ON planning_events(owner_id);
CREATE INDEX idx_planning_events_start_date ON planning_events(start_date);
CREATE INDEX idx_planning_milestones_project ON planning_milestones(project_id);
CREATE INDEX idx_planning_projects_client ON planning_projects(client_id);
CREATE INDEX idx_planning_tasks_assigned ON planning_tasks(assigned_to);
CREATE INDEX idx_planning_tasks_project ON planning_tasks(project_id);
CREATE INDEX idx_po_operations_order ON production_order_operations(production_order_id);
CREATE INDEX idx_po_resources_order ON production_order_resources(production_order_id);
CREATE INDEX idx_pos_returns_sale ON pos_returns(pos_sale_id);
CREATE INDEX idx_pos_sale_items_inv  ON pos_sale_items(inventory_id);
CREATE INDEX idx_pos_sale_items_sale ON pos_sale_items(pos_sale_id);
CREATE INDEX idx_pos_sales_invoice ON pos_sales(invoice_id);
CREATE INDEX idx_pos_sales_session ON pos_sales(session_id);
CREATE INDEX idx_pos_sessions_cashier ON pos_sessions(cashier_id, status);
CREATE INDEX idx_production_order_items_order ON production_order_items(production_order_id);
CREATE INDEX idx_production_orders_due ON production_orders(due_date);
CREATE INDEX idx_production_orders_status ON production_orders(status);
CREATE INDEX idx_production_qc_defects_qc ON production_qc_defects(qc_id);
CREATE INDEX idx_production_qc_order  ON production_qc(production_order_id);
CREATE INDEX idx_production_qc_status ON production_qc(status);
CREATE INDEX idx_purchases_supplier    ON purchases(supplier);
CREATE INDEX idx_purchases_supplier_id ON purchases(supplier_id);
CREATE INDEX idx_quotation_items_quote ON quotation_items(quotation_id);
CREATE INDEX idx_recr_af_app ON recruitment_applicant_files(applicant_id);
CREATE INDEX idx_recr_app_emp      ON recruitment_applicants(converted_employee_id);
CREATE INDEX idx_recr_app_position ON recruitment_applicants(position_id);
CREATE INDEX idx_recr_app_status   ON recruitment_applicants(status);
CREATE INDEX idx_recr_int_app ON recruitment_interviews(applicant_id);
CREATE INDEX idx_recr_int_when ON recruitment_interviews(scheduled_at);
CREATE INDEX idx_recr_pos_dept   ON recruitment_positions(department_id);
CREATE INDEX idx_recr_pos_status ON recruitment_positions(status);
CREATE INDEX idx_recr_sh_app ON recruitment_status_history(applicant_id);
CREATE INDEX idx_recruitment_offers_applicant ON recruitment_offers(applicant_id, archived_at);
CREATE INDEX idx_recruitment_offers_status ON recruitment_offers(status, archived_at);
CREATE INDEX idx_recurring_expenses_active ON recurring_expenses(is_active);
CREATE INDEX idx_roles_name            ON roles(name);
CREATE INDEX idx_sessions_jti          ON user_sessions(jti);
CREATE INDEX idx_sessions_revoked      ON user_sessions(revoked);
CREATE INDEX idx_sessions_user         ON user_sessions(user_id);
CREATE INDEX idx_stock_movements_item  ON stock_movements(inventory_id);
CREATE INDEX idx_transfer_items_transfer ON stock_transfer_items(transfer_id);
CREATE INDEX idx_transfers_status ON stock_transfers(status, created_at);
CREATE UNIQUE INDEX idx_warehouses_one_default ON warehouses(is_default) WHERE is_default=1;

-- ── Migration ledger (these are baked into the baseline above) ────────────
INSERT INTO schema_migrations (name, applied_at) VALUES
    ('001_soft_delete', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('002_invoice_paid_amount', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('003_drop_quotation_payments', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('004_quotation_project_name', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('005_project_expected_revenue', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('006_project_source_quotation', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('007_inventory_unit_cost', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('008_purchases_supplier_id', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('009_invoice_version', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('010_invoice_voided_at', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('011_invoice_void_reason', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('012_payment_idempotency', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('013_users_email', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('014_users_is_active', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('015_users_is_superadmin', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('016_users_role_id', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('017_users_last_login', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('018_users_deleted_at', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('019_users_must_change_pw', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('020_expenses_voided_at', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('021_expenses_void_reason', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('022_archive_columns', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('023_documents', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('024_crm_leads', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('025_crm_contacts', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('026_crm_activities', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('027_crm_deals', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('028_planning_projects', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('029_planning_tasks', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('030_planning_milestones', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('031_notifications', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('032_approval_policies', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('033_approval_requests', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('034_approval_steps', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('035_milestone_archived_at', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('036_expense_status', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('037_approval_comments', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('038_backfill_user_roles', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('039_hr_departments', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('040_hr_employees', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('041_hr_leave_requests', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('042_exchange_rates', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('043_payment_currency', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('044_tax_rates', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('045_line_item_tax', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('046_inventory_barcode', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('047_pos_sessions', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('048_pos_sales', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('049_pos_sale_items', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('050_pos_returns', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('051_inventory_sale_price', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('052_invoice_item_discount', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('053_pos_pricing', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('054_cash_drawers', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('055_cash_reconciliations', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('056_cash_movements', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('057_expense_payment_method', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('058_cash_drawer_attribution', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('059_cash_dual_currency', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('060_pos_session_dual_currency', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('061_boms', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('062_bom_components', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('063_production_orders', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('064_production_order_items', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('065_fixed_assets', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('066_asset_depreciation', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('067_recurring_expenses', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('068_expense_recurring_id', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('069_expense_fixed_asset_id', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('070_mfg_inventory', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('071_mfg_boms', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('072_mfg_bom_group_backfill', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('073_mfg_bom_components', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('074_mfg_orders', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('075_mfg_order_items', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('076_module_requests', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('077_planning_events', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('078_announcements', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('079_event_attendees', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('080_roles_is_admin', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('081_drop_enabled_modules_setting', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('082_drop_module_requests_table', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('083_drop_invoice_writeoff', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('084_crm_leads_archive_reason', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('084_crm_deals_archive_reason', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('084_planning_projects_archive_reason', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('084_planning_tasks_archive_reason', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('085_purchases_category', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('086_quotations_lead_id', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('087_hr_employment_changes', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('088_hr_payroll_runs', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('089_hr_payroll_lines', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('090_hr_employee_files', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('092_recruitment_positions', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('093_recruitment_applicants', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('094_recruitment_status_history', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('095_recruitment_interviews', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('096_recruitment_applicant_files', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('097_hr_contracts', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('098_payroll_lines_tax', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('098_payroll_lines_nssf_emp', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('098_payroll_lines_nssf_co', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('098_payroll_lines_ovt_hours', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('098_payroll_lines_ovt_amount', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('098_payroll_lines_gross', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('098_payroll_runs_tax', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('098_payroll_runs_nssf_emp', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('098_payroll_runs_nssf_co', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('098_payroll_runs_overtime', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('099_notifications_deliver_at', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('100_hr_activities', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('101_recr_interviews_hr_activity_id', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('102_recr_applicants_accepted_reason', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('101_recruitment_offers', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('105_mfg_work_centers', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('106_mfg_qc', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('107_inventory_lots', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('108_mfg_scheduling', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('109_mfg_resources', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('110_fiscal_years', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('102_inventory_cost_layers', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('104_accounting', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('120_multi_currency_accounts', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('121_payroll_line_currency', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('122_warehouses', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('123_quotation_items_discount', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('103_attachments', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('124_attachment_storage', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('125_hr_recruitment_file_storage', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('091_backfill_employment_changes', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('126_hr_attendance', to_char(now(), 'YYYY-MM-DD HH24:MI:SS'))
ON CONFLICT (name) DO NOTHING;
